// <auto-generated />
using System;
using LibSys.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibSys.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250529072231_AddIdentityRoleSupport")]
    partial class AddIdentityRoleSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibSys.Models.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookDefinitionId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6e20e9d-4ab3-4fd1-92cd-734998043266"),
                            BookDefinitionId = new Guid("dfb274b1-e5e7-41ac-b4ab-1a1de518c52b"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("3df28a5c-7b25-49ff-8ec6-9380d58bbe9d"),
                            BookDefinitionId = new Guid("3723afbf-c3bb-4a4a-aadc-739c8af1bb7b"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("83fa1eab-2885-48b3-bcda-6e86c1508be3"),
                            BookDefinitionId = new Guid("6b01b27e-0c4f-47f4-9dd0-2162b51508e0"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("e6761c38-f2c6-4683-bf6d-153988f86ae3"),
                            BookDefinitionId = new Guid("bc8f4a9d-91bc-44f4-813a-c86fcc7b5c83"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("9eca2aee-d62b-4ea5-8bd8-55d964e63530"),
                            BookDefinitionId = new Guid("6951fa30-b5f1-4fd7-b831-1557a6a58cf6"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("c0673e1c-c9ad-4dcf-baf1-e8d05560a996"),
                            BookDefinitionId = new Guid("819c3de3-483f-4223-a8b4-7ac634930de3"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("9a82de7e-bfce-4b00-9a83-2d73604e542e"),
                            BookDefinitionId = new Guid("819c3de3-483f-4223-a8b4-7ac634930de3"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("7949803a-c042-49b5-a74d-447b6da7ec44"),
                            BookDefinitionId = new Guid("9c38aca7-d837-40dc-a9ae-4b66819de030"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("751ba902-f09f-4f43-9ff1-15cb13597ab2"),
                            BookDefinitionId = new Guid("d29c7fcf-864a-4a9d-ae7d-97e8e50e9a12"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("418d3a47-cbc3-4ba8-8eba-343f56e08d70"),
                            BookDefinitionId = new Guid("77e9fd0e-47f1-414d-a1f1-7cccd06f94ef"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("7e5aba99-b5db-4251-9ab3-d15cbb1cfa36"),
                            BookDefinitionId = new Guid("d29c7fcf-864a-4a9d-ae7d-97e8e50e9a12"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d5859648-78d2-4fb2-b4f3-b2913013d06a"),
                            BookDefinitionId = new Guid("4a1f3dd9-ac98-4d0e-b368-b07e2542113d"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("f5b74e80-5f91-4206-a81c-bcbb5a630452"),
                            BookDefinitionId = new Guid("6b01b27e-0c4f-47f4-9dd0-2162b51508e0"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("5625bef7-aa68-4b49-9106-4efa2251634f"),
                            BookDefinitionId = new Guid("819c3de3-483f-4223-a8b4-7ac634930de3"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8479b6c4-f521-45ac-98ff-5a829a02c16b"),
                            BookDefinitionId = new Guid("81b4c419-807a-4d2f-91dc-6abf94183e2c"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("8e57d665-26d0-43fc-88d4-60cb6acadd81"),
                            BookDefinitionId = new Guid("f74e1f65-932a-4091-90fc-23914bd6be2e"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("7f65544d-bbba-4095-91a4-c54bef1a4c00"),
                            BookDefinitionId = new Guid("f76905ac-2e81-49e6-a780-b674d91c0e9b"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ba6bb43d-2744-4fc5-bb4c-bcf5ed9f387c"),
                            BookDefinitionId = new Guid("f87c6b22-dd61-468e-8565-b6d236bc5596"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("bded5e72-2d26-4567-9cab-29c071b8f86e"),
                            BookDefinitionId = new Guid("6b01b27e-0c4f-47f4-9dd0-2162b51508e0"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("49133f99-4649-4872-ae98-4c562996f8a1"),
                            BookDefinitionId = new Guid("9c38aca7-d837-40dc-a9ae-4b66819de030"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("fa16c7f5-e09f-4736-be58-fb26dd4b97b9"),
                            BookDefinitionId = new Guid("afa07347-7c04-46d4-8241-dd969dbccbac"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8d81c53f-a229-466e-bc6c-5e02fee0e011"),
                            BookDefinitionId = new Guid("3a9e3864-109a-4fea-881b-a3e1c0719e7d"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("6866d685-383f-478a-9d93-16523ff13301"),
                            BookDefinitionId = new Guid("dfb274b1-e5e7-41ac-b4ab-1a1de518c52b"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("4036633f-fad8-43e7-bacb-83c65c81859f"),
                            BookDefinitionId = new Guid("410215ae-93bd-4e2e-bb40-613960dca85e"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("116ee288-345e-45ae-8ba6-5d9c7df8f6b7"),
                            BookDefinitionId = new Guid("f87c6b22-dd61-468e-8565-b6d236bc5596"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("6f67f0da-dff4-4570-a59a-3f05044ee4fe"),
                            BookDefinitionId = new Guid("3ce3efa2-c19b-4430-80e5-1a36366a4d1f"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("e2ae0e12-11b3-4802-8db1-b62de44aa283"),
                            BookDefinitionId = new Guid("28472a07-ced7-4e78-ad6e-f6f8f33411ac"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("b508d4ac-d1ee-4911-8101-6465e3edd909"),
                            BookDefinitionId = new Guid("6951fa30-b5f1-4fd7-b831-1557a6a58cf6"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("b5d52925-e699-4ee4-986e-f58fc7bfe5e1"),
                            BookDefinitionId = new Guid("81b4c419-807a-4d2f-91dc-6abf94183e2c"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("81ac4145-5970-43c3-8025-1e2b8e891aa9"),
                            BookDefinitionId = new Guid("591b8158-660a-4918-97c8-04024d921cb9"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("53d7cf33-f14b-405b-b3d4-bbe1f059d459"),
                            BookDefinitionId = new Guid("7ce7c1c3-20d4-46c2-b175-229585df5756"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("4a21e4bd-8ab9-47b3-bbed-064222e65d59"),
                            BookDefinitionId = new Guid("4a1f3dd9-ac98-4d0e-b368-b07e2542113d"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("cd5bf0ab-f21b-4fbb-9fcc-d69778c47d2b"),
                            BookDefinitionId = new Guid("6b01b27e-0c4f-47f4-9dd0-2162b51508e0"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("660f8dc9-86b3-46bb-ba0b-e3e5b069d258"),
                            BookDefinitionId = new Guid("f68add18-030a-48ef-950b-6944914e8ab0"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("4edcecef-c3f2-441a-a9da-f7a601d6dbd1"),
                            BookDefinitionId = new Guid("b8f89091-0e70-4221-a708-778eaedb2b6c"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("0e79a04b-70bc-4f12-b6a4-f62c3f4733ce"),
                            BookDefinitionId = new Guid("6951fa30-b5f1-4fd7-b831-1557a6a58cf6"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d1a2cd43-a87d-49bd-9efd-d60a49b5fafc"),
                            BookDefinitionId = new Guid("410215ae-93bd-4e2e-bb40-613960dca85e"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("67dc1965-14f8-4532-b0c4-3a829745e5b7"),
                            BookDefinitionId = new Guid("b8f89091-0e70-4221-a708-778eaedb2b6c"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("ba5bc79d-1bb7-439d-bb1b-2e0fe6f444fb"),
                            BookDefinitionId = new Guid("afa07347-7c04-46d4-8241-dd969dbccbac"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("69ae25c2-269d-4b31-b61d-a3306efdeabe"),
                            BookDefinitionId = new Guid("3ce3efa2-c19b-4430-80e5-1a36366a4d1f"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("0119151f-1e9f-4dff-bc28-b65b64218483"),
                            BookDefinitionId = new Guid("dfb274b1-e5e7-41ac-b4ab-1a1de518c52b"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("53751848-6eb1-4309-a2d7-603ee677845d"),
                            BookDefinitionId = new Guid("28472a07-ced7-4e78-ad6e-f6f8f33411ac"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("a40a31b4-a136-4313-8a00-753182ba4cbb"),
                            BookDefinitionId = new Guid("81b4c419-807a-4d2f-91dc-6abf94183e2c"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("d97dc7eb-75ab-4b8c-9fdd-5f3dc6714e1d"),
                            BookDefinitionId = new Guid("9c38aca7-d837-40dc-a9ae-4b66819de030"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("720b65ab-f427-4d3d-9d06-68d7e31aa07d"),
                            BookDefinitionId = new Guid("afa07347-7c04-46d4-8241-dd969dbccbac"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("58a5821c-88e8-464f-bc9d-f4eea491293c"),
                            BookDefinitionId = new Guid("f76905ac-2e81-49e6-a780-b674d91c0e9b"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8a938d3a-86ee-460b-8111-7838f715d05d"),
                            BookDefinitionId = new Guid("9c38aca7-d837-40dc-a9ae-4b66819de030"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("f512a108-d17c-4074-9a21-7d70fb4f33d4"),
                            BookDefinitionId = new Guid("7ce7c1c3-20d4-46c2-b175-229585df5756"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("72a4debc-1a67-402a-8bcb-79c55383ff5c"),
                            BookDefinitionId = new Guid("81b4c419-807a-4d2f-91dc-6abf94183e2c"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("cd00945e-6633-4ab3-9b85-c2762bdbe7f8"),
                            BookDefinitionId = new Guid("0d861549-568b-425f-a078-ff64915fba9e"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("321b91c2-c06b-46f3-a773-6188cc1fa082"),
                            BookDefinitionId = new Guid("6d1fc983-bfb4-4b60-a9c3-676290deb47a"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("2f25968c-c628-480f-9854-7125222da1f2"),
                            BookDefinitionId = new Guid("afa07347-7c04-46d4-8241-dd969dbccbac"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("c37404e7-4ae9-4484-aaa3-9b1bbddada19"),
                            BookDefinitionId = new Guid("6b01b27e-0c4f-47f4-9dd0-2162b51508e0"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("47a8c9fd-20a1-4b85-8112-a6725a99e14b"),
                            BookDefinitionId = new Guid("77e9fd0e-47f1-414d-a1f1-7cccd06f94ef"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("b21fd861-83ef-4e4c-b315-31d5c690ba49"),
                            BookDefinitionId = new Guid("3ce3efa2-c19b-4430-80e5-1a36366a4d1f"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("285facd4-ce7e-4791-a402-f875a415fd0d"),
                            BookDefinitionId = new Guid("3ce3efa2-c19b-4430-80e5-1a36366a4d1f"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("21961597-151d-468a-9bd9-92f97bc40473"),
                            BookDefinitionId = new Guid("77e9fd0e-47f1-414d-a1f1-7cccd06f94ef"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d23190df-046b-417f-8fb9-cdc8f07fcb1a"),
                            BookDefinitionId = new Guid("819c3de3-483f-4223-a8b4-7ac634930de3"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("7c5aa709-dd4f-4c7a-80de-9153fca4644f"),
                            BookDefinitionId = new Guid("4a1f3dd9-ac98-4d0e-b368-b07e2542113d"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("47030a08-65ab-49a6-89b6-dae59324ae33"),
                            BookDefinitionId = new Guid("3a9e3864-109a-4fea-881b-a3e1c0719e7d"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ea233f86-34d6-44ee-ab5f-4ff7fa0dca02"),
                            BookDefinitionId = new Guid("28472a07-ced7-4e78-ad6e-f6f8f33411ac"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("5a77e5e9-b615-4391-a582-f190d93aa135"),
                            BookDefinitionId = new Guid("e743a086-aa56-470e-8cb9-abb62d10208c"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("1f197941-ed4c-4cdf-97c2-73de5f27480e"),
                            BookDefinitionId = new Guid("6b01b27e-0c4f-47f4-9dd0-2162b51508e0"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("3f0f998b-c763-42fc-b6b0-d70e908e3c6c"),
                            BookDefinitionId = new Guid("e743a086-aa56-470e-8cb9-abb62d10208c"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("e791583d-0923-4557-b117-25f066b9ce3e"),
                            BookDefinitionId = new Guid("f76905ac-2e81-49e6-a780-b674d91c0e9b"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("052698ea-ea1f-451e-a0ec-110bcea9c50f"),
                            BookDefinitionId = new Guid("28472a07-ced7-4e78-ad6e-f6f8f33411ac"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("009fb077-9761-4d33-9c73-ec4c77af18a5"),
                            BookDefinitionId = new Guid("dfb274b1-e5e7-41ac-b4ab-1a1de518c52b"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("14c2a934-25f9-4b22-a438-a0a7c29a84a4"),
                            BookDefinitionId = new Guid("410215ae-93bd-4e2e-bb40-613960dca85e"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("179f4cb7-881d-44d6-bcd4-b61807e7aa35"),
                            BookDefinitionId = new Guid("f87c6b22-dd61-468e-8565-b6d236bc5596"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("79500cf5-6620-4a00-9aa2-3cdf96d6e7ad"),
                            BookDefinitionId = new Guid("7ce7c1c3-20d4-46c2-b175-229585df5756"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("98a0b921-86f4-469d-936f-8895e5b4d531"),
                            BookDefinitionId = new Guid("410215ae-93bd-4e2e-bb40-613960dca85e"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("229d9dd8-d26d-44e9-8002-3ff3bd6a8c8c"),
                            BookDefinitionId = new Guid("f74e1f65-932a-4091-90fc-23914bd6be2e"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("2be051ad-d1dc-4580-9525-228225e9e1ff"),
                            BookDefinitionId = new Guid("e743a086-aa56-470e-8cb9-abb62d10208c"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("6b0589d2-8d5b-4e75-b874-91b226129339"),
                            BookDefinitionId = new Guid("819c3de3-483f-4223-a8b4-7ac634930de3"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("3e5bbec0-6770-4943-87b9-a10b9cbdee40"),
                            BookDefinitionId = new Guid("6d1fc983-bfb4-4b60-a9c3-676290deb47a"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("e648ce58-5c2c-41d3-8c38-9bfdb6bfc268"),
                            BookDefinitionId = new Guid("51697d68-4f1d-4dd0-9165-759322a1273f"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ed331ec6-673c-4445-bb39-07ef737faae6"),
                            BookDefinitionId = new Guid("198d2b19-50f2-4434-b04c-33a6cbe2f4dd"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("5f2773aa-8b00-447a-9322-2216963d231a"),
                            BookDefinitionId = new Guid("3ce3efa2-c19b-4430-80e5-1a36366a4d1f"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("7d04fdc7-34df-4f05-a1d6-d05d9ab43327"),
                            BookDefinitionId = new Guid("81b4c419-807a-4d2f-91dc-6abf94183e2c"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("1da2e1a9-5f1e-4543-8d65-45fbdbc85160"),
                            BookDefinitionId = new Guid("81b4c419-807a-4d2f-91dc-6abf94183e2c"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("fcd5ddbc-c815-457f-b1ce-a4ad8f10484c"),
                            BookDefinitionId = new Guid("6d1fc983-bfb4-4b60-a9c3-676290deb47a"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("9c849553-1383-41f9-b49a-e062977be6db"),
                            BookDefinitionId = new Guid("f74e1f65-932a-4091-90fc-23914bd6be2e"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("64131acf-e2d7-4cb0-bc87-ced22c1c4ef0"),
                            BookDefinitionId = new Guid("f74e1f65-932a-4091-90fc-23914bd6be2e"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("461a9813-ffcc-4644-8340-0171913abfeb"),
                            BookDefinitionId = new Guid("1462068c-ded0-4129-9d47-62e23c665b78"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("7c1221fd-97a0-4cc0-aab4-ca50c29ed38e"),
                            BookDefinitionId = new Guid("f68add18-030a-48ef-950b-6944914e8ab0"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("8c4c88af-09b1-4eec-acd3-0b9cb34081fa"),
                            BookDefinitionId = new Guid("9c38aca7-d837-40dc-a9ae-4b66819de030"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("894a9329-9b80-4075-b2cf-2a3a8848679c"),
                            BookDefinitionId = new Guid("410215ae-93bd-4e2e-bb40-613960dca85e"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("7980be9f-489b-4d6a-9ae1-034b41921f7c"),
                            BookDefinitionId = new Guid("6b01b27e-0c4f-47f4-9dd0-2162b51508e0"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("fb98db2a-652d-4a6e-a0b7-cd266a3fabd7"),
                            BookDefinitionId = new Guid("1462068c-ded0-4129-9d47-62e23c665b78"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("fde7811e-9b87-4806-a2d5-ddc024a6705c"),
                            BookDefinitionId = new Guid("afa07347-7c04-46d4-8241-dd969dbccbac"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("a360d498-dfec-4d25-a4a2-035646b2d8dc"),
                            BookDefinitionId = new Guid("4a1f3dd9-ac98-4d0e-b368-b07e2542113d"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("a9f5c3e7-477d-453b-8326-25a2550e8c4d"),
                            BookDefinitionId = new Guid("6951fa30-b5f1-4fd7-b831-1557a6a58cf6"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("9a2bb7e2-0d02-4ca0-bd57-6753fdb0a333"),
                            BookDefinitionId = new Guid("591b8158-660a-4918-97c8-04024d921cb9"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("1019d28c-87f8-4907-82f4-7a950ba66aaf"),
                            BookDefinitionId = new Guid("f74e1f65-932a-4091-90fc-23914bd6be2e"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("8a495b1e-c984-4c60-af60-2446634a6f80"),
                            BookDefinitionId = new Guid("9c38aca7-d837-40dc-a9ae-4b66819de030"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8e7c2539-98d3-498e-b1f0-48f0b8591de6"),
                            BookDefinitionId = new Guid("0d861549-568b-425f-a078-ff64915fba9e"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("596f5c30-d1de-4ba7-a3ac-67737f83c921"),
                            BookDefinitionId = new Guid("51697d68-4f1d-4dd0-9165-759322a1273f"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("0fb9780a-8d68-4032-bcff-f00fb41aab5e"),
                            BookDefinitionId = new Guid("591b8158-660a-4918-97c8-04024d921cb9"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("fc5cb925-b360-44f8-93fa-3cfde09132ea"),
                            BookDefinitionId = new Guid("f76905ac-2e81-49e6-a780-b674d91c0e9b"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("aeae4385-1395-42dd-bc73-ed2694b58c24"),
                            BookDefinitionId = new Guid("198d2b19-50f2-4434-b04c-33a6cbe2f4dd"),
                            Status = 0
                        });
                });

            modelBuilder.Entity("LibSys.Models.Entities.BookDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dfb274b1-e5e7-41ac-b4ab-1a1de518c52b"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i Kamień Filozoficzny"
                        },
                        new
                        {
                            Id = new Guid("afa07347-7c04-46d4-8241-dd969dbccbac"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i Komnata Tajemnic"
                        },
                        new
                        {
                            Id = new Guid("1462068c-ded0-4129-9d47-62e23c665b78"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i więzień Azkabanu"
                        },
                        new
                        {
                            Id = new Guid("6b01b27e-0c4f-47f4-9dd0-2162b51508e0"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i Czara Ognia"
                        },
                        new
                        {
                            Id = new Guid("819c3de3-483f-4223-a8b4-7ac634930de3"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i Zakon Feniksa"
                        },
                        new
                        {
                            Id = new Guid("591b8158-660a-4918-97c8-04024d921cb9"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i Książę Półkrwi"
                        },
                        new
                        {
                            Id = new Guid("198d2b19-50f2-4434-b04c-33a6cbe2f4dd"),
                            Author = "Stieg Larsson",
                            Title = "Mężczyźni, którzy nienawidzą kobiet"
                        },
                        new
                        {
                            Id = new Guid("3723afbf-c3bb-4a4a-aadc-739c8af1bb7b"),
                            Author = "George R.R. Martin",
                            Title = "Gra o tron (edycja ilustrowana)"
                        },
                        new
                        {
                            Id = new Guid("d29c7fcf-864a-4a9d-ae7d-97e8e50e9a12"),
                            Author = "William Shakespeare",
                            Title = "Romeo i Julia"
                        },
                        new
                        {
                            Id = new Guid("f76905ac-2e81-49e6-a780-b674d91c0e9b"),
                            Author = "George R.R. Martin",
                            Title = "Starcie królów (edycja ilustrowana)"
                        },
                        new
                        {
                            Id = new Guid("410215ae-93bd-4e2e-bb40-613960dca85e"),
                            Author = "Camilla Läckberg",
                            Title = "Księżniczka z lodu"
                        },
                        new
                        {
                            Id = new Guid("3ce3efa2-c19b-4430-80e5-1a36366a4d1f"),
                            Author = "George R.R. Martin",
                            Title = "Nawałnica mieczy: Stal i śnieg"
                        },
                        new
                        {
                            Id = new Guid("77e9fd0e-47f1-414d-a1f1-7cccd06f94ef"),
                            Author = "Johann Wolfgang von Goethe",
                            Title = "Cierpienia młodego Wertera"
                        },
                        new
                        {
                            Id = new Guid("28472a07-ced7-4e78-ad6e-f6f8f33411ac"),
                            Author = "Veronica Roth",
                            Title = "Niezgodna"
                        },
                        new
                        {
                            Id = new Guid("bc8f4a9d-91bc-44f4-813a-c86fcc7b5c83"),
                            Author = "J.K. Rowling, Jack Thorne",
                            Title = "Harry Potter i Przeklęte Dziecko"
                        },
                        new
                        {
                            Id = new Guid("f68add18-030a-48ef-950b-6944914e8ab0"),
                            Author = "Juliusz Słowacki",
                            Title = "Balladyna"
                        },
                        new
                        {
                            Id = new Guid("6d1fc983-bfb4-4b60-a9c3-676290deb47a"),
                            Author = "Camilla Läckberg",
                            Title = "Kaznodzieja"
                        },
                        new
                        {
                            Id = new Guid("e743a086-aa56-470e-8cb9-abb62d10208c"),
                            Author = "Dan Brown",
                            Title = "Inferno"
                        },
                        new
                        {
                            Id = new Guid("3a9e3864-109a-4fea-881b-a3e1c0719e7d"),
                            Author = "Stanisław Wyspiański",
                            Title = "Wesele"
                        },
                        new
                        {
                            Id = new Guid("9c38aca7-d837-40dc-a9ae-4b66819de030"),
                            Author = "Camilla Läckberg",
                            Title = "Kamieniarz"
                        },
                        new
                        {
                            Id = new Guid("51697d68-4f1d-4dd0-9165-759322a1273f"),
                            Author = "Jo Nesbø",
                            Title = "Człowiek nietoperz"
                        },
                        new
                        {
                            Id = new Guid("f74e1f65-932a-4091-90fc-23914bd6be2e"),
                            Author = "Juliusz Słowacki",
                            Title = "Kordian"
                        },
                        new
                        {
                            Id = new Guid("81b4c419-807a-4d2f-91dc-6abf94183e2c"),
                            Author = "Andrzej Sapkowski",
                            Title = "Narrenturm"
                        },
                        new
                        {
                            Id = new Guid("ae2628ef-e2b9-477e-8b33-98076fe89823"),
                            Author = "Kornel Makuszyński",
                            Title = "Szatan z siódmej klasy"
                        },
                        new
                        {
                            Id = new Guid("7ce7c1c3-20d4-46c2-b175-229585df5756"),
                            Author = "Camilla Läckberg",
                            Title = "Ofiara losu"
                        },
                        new
                        {
                            Id = new Guid("0d861549-568b-425f-a078-ff64915fba9e"),
                            Author = "Cassandra Clare",
                            Title = "Miasto upadłych aniołów"
                        },
                        new
                        {
                            Id = new Guid("6951fa30-b5f1-4fd7-b831-1557a6a58cf6"),
                            Author = "Camilla Läckberg",
                            Title = "Niemiecki bękart"
                        },
                        new
                        {
                            Id = new Guid("f87c6b22-dd61-468e-8565-b6d236bc5596"),
                            Author = "Władysław Stanisław Reymont",
                            Title = "Chłopi"
                        },
                        new
                        {
                            Id = new Guid("4a1f3dd9-ac98-4d0e-b368-b07e2542113d"),
                            Author = "Andrzej Ziemiański",
                            Title = "Achaja. Tom I"
                        },
                        new
                        {
                            Id = new Guid("b8f89091-0e70-4221-a708-778eaedb2b6c"),
                            Author = "Christopher Paolini",
                            Title = "Dziedzictwo"
                        });
                });

            modelBuilder.Entity("LibSys.Models.Entities.Borrowing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("ReaderId");

                    b.ToTable("Borrowings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("29480d1c-8fd4-40ec-83c8-80e4a866cff3"),
                            BookId = new Guid("3df28a5c-7b25-49ff-8ec6-9380d58bbe9d"),
                            BorrowDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("6ef43601-4194-4b07-a2c3-fee8637af4cf"),
                            ReturnDate = new DateTime(2025, 7, 2, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("42b6f07a-cfce-4993-9aaf-f688ffb871e6"),
                            BookId = new Guid("9eca2aee-d62b-4ea5-8bd8-55d964e63530"),
                            BorrowDate = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("b12d8bfe-245e-4967-a3f9-8e780c2806e3"),
                            ReturnDate = new DateTime(2025, 7, 7, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("cfa34d2f-6bde-4a26-b381-1d076295088e"),
                            BookId = new Guid("751ba902-f09f-4f43-9ff1-15cb13597ab2"),
                            BorrowDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("6ef43601-4194-4b07-a2c3-fee8637af4cf"),
                            ReturnDate = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("8c1b16cb-5810-48a1-81c9-200ecdf0dead"),
                            BookId = new Guid("d5859648-78d2-4fb2-b4f3-b2913013d06a"),
                            BorrowDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("85d3f82a-c4c6-42e7-af13-9528218d14fe"),
                            ReturnDate = new DateTime(2025, 7, 11, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("f3f9fff2-f565-4588-a4e3-ff7b81882094"),
                            BookId = new Guid("f5b74e80-5f91-4206-a81c-bcbb5a630452"),
                            BorrowDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2025, 7, 6, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("1b0b94b4-19c8-4179-847c-acdde42eb893"),
                            BookId = new Guid("8479b6c4-f521-45ac-98ff-5a829a02c16b"),
                            BorrowDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("7090bb20-524c-489e-8017-0d7b09f42542"),
                            BookId = new Guid("ba6bb43d-2744-4fc5-bb4c-bcf5ed9f387c"),
                            BorrowDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("85d3f82a-c4c6-42e7-af13-9528218d14fe"),
                            ReturnDate = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("66fbb366-83dc-4bdb-99f1-bf1b0627d02d"),
                            BookId = new Guid("bded5e72-2d26-4567-9cab-29c071b8f86e"),
                            BorrowDate = new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2025, 7, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("6bd07fcf-6c59-45c3-9660-bd5a06c7c259"),
                            BookId = new Guid("49133f99-4649-4872-ae98-4c562996f8a1"),
                            BorrowDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("6ef43601-4194-4b07-a2c3-fee8637af4cf"),
                            ReturnDate = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("f8c68237-2726-41a6-aa86-4e3862155c2a"),
                            BookId = new Guid("4036633f-fad8-43e7-bacb-83c65c81859f"),
                            BorrowDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("b12d8bfe-245e-4967-a3f9-8e780c2806e3"),
                            ReturnDate = new DateTime(2025, 7, 6, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("19c5b850-5919-4160-939e-96ae54cd2384"),
                            BookId = new Guid("e2ae0e12-11b3-4802-8db1-b62de44aa283"),
                            BorrowDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("3d82ce65-5b07-47dd-a7d5-3a7a17ba6dcf"),
                            BookId = new Guid("b508d4ac-d1ee-4911-8101-6465e3edd909"),
                            BorrowDate = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("85d3f82a-c4c6-42e7-af13-9528218d14fe"),
                            ReturnDate = new DateTime(2025, 7, 13, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("8696a621-725d-418a-a9f1-2947e0b68b71"),
                            BookId = new Guid("b5d52925-e699-4ee4-986e-f58fc7bfe5e1"),
                            BorrowDate = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("b12d8bfe-245e-4967-a3f9-8e780c2806e3"),
                            ReturnDate = new DateTime(2025, 7, 7, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("ee186178-6257-48de-9adc-a958701c4a2b"),
                            BookId = new Guid("660f8dc9-86b3-46bb-ba0b-e3e5b069d258"),
                            BorrowDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("b12d8bfe-245e-4967-a3f9-8e780c2806e3"),
                            ReturnDate = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("9e40f2a7-5df0-4530-a53d-82ffde4be843"),
                            BookId = new Guid("67dc1965-14f8-4532-b0c4-3a829745e5b7"),
                            BorrowDate = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2025, 7, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("99e98e73-1e68-4d85-bcd1-83ea7a06c27b"),
                            BookId = new Guid("69ae25c2-269d-4b31-b61d-a3306efdeabe"),
                            BorrowDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("b12d8bfe-245e-4967-a3f9-8e780c2806e3"),
                            ReturnDate = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("2fa140c8-709f-499c-9dc3-d2b1519a3069"),
                            BookId = new Guid("53751848-6eb1-4309-a2d7-603ee677845d"),
                            BorrowDate = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2025, 7, 7, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("986d8f2b-ad34-4de5-99e8-ed89f14f5aaa"),
                            BookId = new Guid("a40a31b4-a136-4313-8a00-753182ba4cbb"),
                            BorrowDate = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("b12d8bfe-245e-4967-a3f9-8e780c2806e3"),
                            ReturnDate = new DateTime(2025, 6, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("d479fa4e-a0a1-4268-869b-c818b760c1d9"),
                            BookId = new Guid("720b65ab-f427-4d3d-9d06-68d7e31aa07d"),
                            BorrowDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("85d3f82a-c4c6-42e7-af13-9528218d14fe"),
                            ReturnDate = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("16626b58-8ffe-4914-a2c5-2b9503f512eb"),
                            BookId = new Guid("cd00945e-6633-4ab3-9b85-c2762bdbe7f8"),
                            BorrowDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("6ef43601-4194-4b07-a2c3-fee8637af4cf"),
                            ReturnDate = new DateTime(2025, 7, 2, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("51b0697f-bac5-40dd-94b6-7f158cd041ca"),
                            BookId = new Guid("2f25968c-c628-480f-9854-7125222da1f2"),
                            BorrowDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("b12d8bfe-245e-4967-a3f9-8e780c2806e3"),
                            ReturnDate = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("4d151503-a229-4edb-8288-cf50da0583a0"),
                            BookId = new Guid("7c5aa709-dd4f-4c7a-80de-9153fca4644f"),
                            BorrowDate = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("85d3f82a-c4c6-42e7-af13-9528218d14fe"),
                            ReturnDate = new DateTime(2025, 7, 13, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("20fcef83-8104-4061-b502-5db3c8430524"),
                            BookId = new Guid("ea233f86-34d6-44ee-ab5f-4ff7fa0dca02"),
                            BorrowDate = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("85d3f82a-c4c6-42e7-af13-9528218d14fe"),
                            ReturnDate = new DateTime(2025, 6, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("864a4954-3779-46f1-b06b-cd40bcefe916"),
                            BookId = new Guid("1f197941-ed4c-4cdf-97c2-73de5f27480e"),
                            BorrowDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("85d3f82a-c4c6-42e7-af13-9528218d14fe"),
                            ReturnDate = new DateTime(2025, 7, 2, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("32000e78-2476-4af8-9b36-0e637a5c0fbf"),
                            BookId = new Guid("179f4cb7-881d-44d6-bcd4-b61807e7aa35"),
                            BorrowDate = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2025, 7, 7, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("1e7cbe21-318b-47b2-8dda-efd9830c13c4"),
                            BookId = new Guid("3e5bbec0-6770-4943-87b9-a10b9cbdee40"),
                            BorrowDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("85d3f82a-c4c6-42e7-af13-9528218d14fe"),
                            ReturnDate = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("735d21fb-c789-4b42-a59b-46cca70d6003"),
                            BookId = new Guid("5f2773aa-8b00-447a-9322-2216963d231a"),
                            BorrowDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("85d3f82a-c4c6-42e7-af13-9528218d14fe"),
                            ReturnDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("75ab01a4-db49-48b1-9467-d8675fad2189"),
                            BookId = new Guid("7d04fdc7-34df-4f05-a1d6-d05d9ab43327"),
                            BorrowDate = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("85d3f82a-c4c6-42e7-af13-9528218d14fe"),
                            ReturnDate = new DateTime(2025, 7, 7, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("d753b49b-cf88-44b7-a6c0-6416aa67a780"),
                            BookId = new Guid("64131acf-e2d7-4cb0-bc87-ced22c1c4ef0"),
                            BorrowDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("85d3f82a-c4c6-42e7-af13-9528218d14fe"),
                            ReturnDate = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("d0851b23-1ca4-4f94-b9c4-218c938c7fc7"),
                            BookId = new Guid("7980be9f-489b-4d6a-9ae1-034b41921f7c"),
                            BorrowDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("85d3f82a-c4c6-42e7-af13-9528218d14fe"),
                            ReturnDate = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("9439f8ab-ab23-4fc5-8461-aa026a314f9e"),
                            BookId = new Guid("fb98db2a-652d-4a6e-a0b7-cd266a3fabd7"),
                            BorrowDate = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("b12d8bfe-245e-4967-a3f9-8e780c2806e3"),
                            ReturnDate = new DateTime(2025, 6, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("24be92f4-863e-4b62-8482-c3e1e664341f"),
                            BookId = new Guid("fde7811e-9b87-4806-a2d5-ddc024a6705c"),
                            BorrowDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2025, 7, 6, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("adbbc54b-9430-4192-b797-01fbc231f828"),
                            BookId = new Guid("596f5c30-d1de-4ba7-a3ac-67737f83c921"),
                            BorrowDate = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2025, 7, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("71bc9398-aea6-4171-8515-2030e2251a0b"),
                            BookId = new Guid("fc5cb925-b360-44f8-93fa-3cfde09132ea"),
                            BorrowDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("b12d8bfe-245e-4967-a3f9-8e780c2806e3"),
                            ReturnDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("LibSys.Models.Entities.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityChanges")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MethodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("LibSys.Models.Entities.Reader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Readers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            City = "Poznań",
                            Code = "61-842",
                            Name = "Jan Kowalski",
                            Street = "Za Bramką 12"
                        },
                        new
                        {
                            Id = new Guid("6ef43601-4194-4b07-a2c3-fee8637af4cf"),
                            City = "Poznań",
                            Code = "61-111",
                            Name = "Tomasz Rydz",
                            Street = "Garbary 1"
                        },
                        new
                        {
                            Id = new Guid("b12d8bfe-245e-4967-a3f9-8e780c2806e3"),
                            City = "Poznań",
                            Code = "61-111",
                            Name = "Aleksandra Mechrzycka",
                            Street = "Solna 2"
                        },
                        new
                        {
                            Id = new Guid("85d3f82a-c4c6-42e7-af13-9528218d14fe"),
                            City = "Poznań",
                            Code = "61-311",
                            Name = "Jan Nowak",
                            Street = "Wieżowa 3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8398a233-f6b9-4361-977c-da6a3e9c2bbe",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "6413944e-a5d8-430e-9a85-a914f5cb349b",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b74ddd14-6340-4840-95c2-db12554843e5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3dc9ebbc-5922-4be0-a806-db5d353b2e68",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPjPmy8yb6w+Bgexl67VP5CITdKaaGr+P0eU5kQHHiiqbQmVWhHkg05Zy61WNHE5pA==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "92c3ef5c-53bd-4d53-abd7-a222c777bc07",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "b74ddd14-6340-4840-95c2-db12554843e5",
                            RoleId = "8398a233-f6b9-4361-977c-da6a3e9c2bbe"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LibSys.Models.Entities.Book", b =>
                {
                    b.HasOne("LibSys.Models.Entities.BookDefinition", "BookDefinition")
                        .WithMany()
                        .HasForeignKey("BookDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookDefinition");
                });

            modelBuilder.Entity("LibSys.Models.Entities.Borrowing", b =>
                {
                    b.HasOne("LibSys.Models.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibSys.Models.Entities.Reader", "Reader")
                        .WithMany()
                        .HasForeignKey("ReaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("LibSys.Models.Entities.Reader", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
