// <auto-generated />
using System;
using LibSys.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibSys.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250614153319_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibSys.Models.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookDefinitionId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f8fceddd-1d9e-48e1-9b40-740b0ab03e83"),
                            BookDefinitionId = new Guid("cdf00e59-8e6f-4baf-aacc-c71a1e2bb25a"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ee8daf79-6bd1-46f1-ba70-35b583abfdc6"),
                            BookDefinitionId = new Guid("618a6b7e-93d5-4996-b436-863c09d81da7"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("c582778e-8c6f-4c52-84f7-7d01eb2e3a6f"),
                            BookDefinitionId = new Guid("618a6b7e-93d5-4996-b436-863c09d81da7"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("6ddade96-4f35-4b8d-996f-914f6c5c45e8"),
                            BookDefinitionId = new Guid("5390d6ee-4110-4afe-8973-282da308c7e2"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("f6fdf555-7445-4a25-8313-d020fc757144"),
                            BookDefinitionId = new Guid("4e23c486-b467-4454-95b0-cced2943d907"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("1243510f-33ad-4cfe-977d-f97096cf7912"),
                            BookDefinitionId = new Guid("618a6b7e-93d5-4996-b436-863c09d81da7"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("7dc1c55f-52b9-44ee-9afb-566661cb6b08"),
                            BookDefinitionId = new Guid("d5ed9c9a-a30f-43fd-b1ee-eb734c09c63f"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("42e6f167-1f31-43f4-8c42-25ee594b8827"),
                            BookDefinitionId = new Guid("53ead14f-b23e-45cc-a972-1dc24e9a3424"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("1402fcb6-68c3-4e8e-9754-435fd067bf52"),
                            BookDefinitionId = new Guid("aa5d87f3-cdc3-4631-a983-4d62834e4fb3"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("7df14d9f-7a50-4c6c-b673-4f37c02b4ea4"),
                            BookDefinitionId = new Guid("618a6b7e-93d5-4996-b436-863c09d81da7"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("f815c08a-8040-44be-9a6e-a24df7754312"),
                            BookDefinitionId = new Guid("78fd8609-958a-404a-8e76-ad9620e6bb03"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("0d3352c1-64d0-484a-b2e3-380077d07901"),
                            BookDefinitionId = new Guid("d21ca2bc-1dab-463e-8bb5-1512054a3ba7"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("e4501d98-cfc9-44e1-a976-0b4087076a59"),
                            BookDefinitionId = new Guid("b6852f11-8ba9-4064-b4d7-10390ae65107"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("aa9ea010-251c-432a-a419-758ea1449d08"),
                            BookDefinitionId = new Guid("618a6b7e-93d5-4996-b436-863c09d81da7"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("fd85325e-b232-4b3c-a7f0-7f9cdb2e9ac1"),
                            BookDefinitionId = new Guid("d5ed9c9a-a30f-43fd-b1ee-eb734c09c63f"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("b4339544-5e4d-4bd8-9bab-bfcbcef352e2"),
                            BookDefinitionId = new Guid("f1d275eb-c762-4af8-8148-4f3eaca07b3a"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("1282ab03-1eee-452a-b0b1-ed33a3919b99"),
                            BookDefinitionId = new Guid("618a6b7e-93d5-4996-b436-863c09d81da7"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("b379ec81-a3fe-4632-bb79-c1191da2cd81"),
                            BookDefinitionId = new Guid("f1d275eb-c762-4af8-8148-4f3eaca07b3a"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d343aa12-27bc-4e12-ba0d-f92ea5016348"),
                            BookDefinitionId = new Guid("aa5d87f3-cdc3-4631-a983-4d62834e4fb3"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("be89ac0c-e9dc-4f0c-a3db-1ea562385fd4"),
                            BookDefinitionId = new Guid("618a6b7e-93d5-4996-b436-863c09d81da7"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("0fd2b647-d423-425f-871b-2765fd4af17e"),
                            BookDefinitionId = new Guid("a8e541b1-398f-4f33-8290-bb6130bd81c8"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("c708f6d4-ab95-4c05-a0cf-335d140fb7fe"),
                            BookDefinitionId = new Guid("a8e541b1-398f-4f33-8290-bb6130bd81c8"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("17dd14f0-d15f-42b2-bd2d-8334302f4b45"),
                            BookDefinitionId = new Guid("655d042a-d318-406a-8412-ab7250c5fcaa"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("92146115-0a43-4aba-9f03-a4d16dff657c"),
                            BookDefinitionId = new Guid("07913eae-9ea9-4414-8aa2-03095767cf21"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("7ebf04b7-695f-49ce-81c6-9b295766f1d6"),
                            BookDefinitionId = new Guid("f1d275eb-c762-4af8-8148-4f3eaca07b3a"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("2ba1a9b1-bdf5-4483-b90f-9b7dafdd4134"),
                            BookDefinitionId = new Guid("4e23c486-b467-4454-95b0-cced2943d907"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ffe10b9e-a727-4cb4-b2dc-07de9860f364"),
                            BookDefinitionId = new Guid("2d0b7b52-4660-43c5-af33-5e545151d9e1"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("03f2d87a-6791-4741-b863-d2a1c6df02a0"),
                            BookDefinitionId = new Guid("5390d6ee-4110-4afe-8973-282da308c7e2"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("24c14d23-1836-43b7-b3b3-df3bb562af91"),
                            BookDefinitionId = new Guid("0c60955d-53e8-4563-8c47-2cc681c72a43"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("e5618def-55b6-492a-8799-a308504a858b"),
                            BookDefinitionId = new Guid("aa5d87f3-cdc3-4631-a983-4d62834e4fb3"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("dac626bb-f546-485d-ada0-929a65482542"),
                            BookDefinitionId = new Guid("f1d275eb-c762-4af8-8148-4f3eaca07b3a"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("adcba8af-d725-4ae9-8d03-a1231aa1d260"),
                            BookDefinitionId = new Guid("aa5d87f3-cdc3-4631-a983-4d62834e4fb3"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("0a44edaa-5697-44ab-b8ab-7c08b497acd4"),
                            BookDefinitionId = new Guid("655d042a-d318-406a-8412-ab7250c5fcaa"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("1f2f7987-198b-40cf-a0a5-3b20b4518a66"),
                            BookDefinitionId = new Guid("f1d275eb-c762-4af8-8148-4f3eaca07b3a"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("f6300740-1025-4dec-898f-cce0e6f68103"),
                            BookDefinitionId = new Guid("acbe8d8c-0823-467a-9aff-7a5b8ca0176e"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("d48daad4-7925-4788-83fa-e688c1c2d0a4"),
                            BookDefinitionId = new Guid("0c60955d-53e8-4563-8c47-2cc681c72a43"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("2e2a1e35-621a-4181-b898-6a08e9a4e9ad"),
                            BookDefinitionId = new Guid("d21ca2bc-1dab-463e-8bb5-1512054a3ba7"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("b21f7b8c-56cc-4d35-a56c-a5ffa91be616"),
                            BookDefinitionId = new Guid("aa5d87f3-cdc3-4631-a983-4d62834e4fb3"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("6cb61164-2384-45df-a8ff-5850ed9212ca"),
                            BookDefinitionId = new Guid("e98ff57a-788c-4bff-97f8-49dc00742736"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("92bfb811-965a-42a7-b55d-6812679fd610"),
                            BookDefinitionId = new Guid("d21ca2bc-1dab-463e-8bb5-1512054a3ba7"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("e77acec1-f669-4c72-87fd-9d103304c1e6"),
                            BookDefinitionId = new Guid("5390d6ee-4110-4afe-8973-282da308c7e2"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("63ab595b-668b-4c1f-8f90-40d1f3386e34"),
                            BookDefinitionId = new Guid("bdad4fb2-d095-498c-8273-fa19ac17d799"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("68d14cd9-7ecd-417f-bf6b-59548d028bbc"),
                            BookDefinitionId = new Guid("d5ed9c9a-a30f-43fd-b1ee-eb734c09c63f"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("35f4f434-363b-48ef-9bbe-da2104771b4e"),
                            BookDefinitionId = new Guid("4e23c486-b467-4454-95b0-cced2943d907"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("718b8bc8-7a8a-4951-9c97-1546cab4fdc5"),
                            BookDefinitionId = new Guid("612ab7d8-20e7-4200-8412-85b66b15fef0"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("77b19b20-e03d-4489-a278-035c19eb64fe"),
                            BookDefinitionId = new Guid("f1d275eb-c762-4af8-8148-4f3eaca07b3a"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("7a9a18d2-00b3-4b90-894b-da37a09d5e70"),
                            BookDefinitionId = new Guid("a8e541b1-398f-4f33-8290-bb6130bd81c8"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("3cca77c9-905e-4d03-9cd9-c62116b192d6"),
                            BookDefinitionId = new Guid("e23a5b30-4b9f-489c-b1ca-d82ec805aace"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("490d4c28-d160-4985-bbf3-c3dd816e5687"),
                            BookDefinitionId = new Guid("f1559d9f-ca57-4ebe-994b-3b3313b11f54"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("36efaff9-67e1-4a8e-b435-f524a61e21a8"),
                            BookDefinitionId = new Guid("07913eae-9ea9-4414-8aa2-03095767cf21"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("85504c8d-2d90-4a4f-8d28-2c7ab48f5924"),
                            BookDefinitionId = new Guid("7cb5de95-bcb7-4b29-a905-a4948f684804"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("947b882f-f1de-4f05-bafd-e76ade1f9115"),
                            BookDefinitionId = new Guid("9b15f13d-4b31-4735-aa18-3fcacfa550fe"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("26d05eb0-ece9-4b0e-a23f-4af0ef75c0e5"),
                            BookDefinitionId = new Guid("cdf00e59-8e6f-4baf-aacc-c71a1e2bb25a"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("571a6bfd-df71-41c8-8ae2-1ab45996587f"),
                            BookDefinitionId = new Guid("c84c9e9c-c249-4225-bb57-24e639f691a4"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("dcf6a437-a2e9-4f07-8b94-be6f87760c4a"),
                            BookDefinitionId = new Guid("9b15f13d-4b31-4735-aa18-3fcacfa550fe"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("9b374c38-1e4b-424b-85b3-9dd528279ad2"),
                            BookDefinitionId = new Guid("612ab7d8-20e7-4200-8412-85b66b15fef0"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("9c606f65-4b1f-4c05-a099-a251b81d9f2b"),
                            BookDefinitionId = new Guid("5390d6ee-4110-4afe-8973-282da308c7e2"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("c62cf2d8-1175-411f-92a0-fe6ac4bcb771"),
                            BookDefinitionId = new Guid("2d0b7b52-4660-43c5-af33-5e545151d9e1"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("aea865ed-d0f5-435e-adaf-929ac8fbbcf1"),
                            BookDefinitionId = new Guid("53ead14f-b23e-45cc-a972-1dc24e9a3424"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("537c3ae5-9ddf-4298-aef6-75d6e185a71f"),
                            BookDefinitionId = new Guid("2d0b7b52-4660-43c5-af33-5e545151d9e1"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a4498221-c3e0-4141-a23c-254f49a89ebb"),
                            BookDefinitionId = new Guid("07913eae-9ea9-4414-8aa2-03095767cf21"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("6c7ab22c-6147-40fe-ac16-60d3f1b724e5"),
                            BookDefinitionId = new Guid("9b15f13d-4b31-4735-aa18-3fcacfa550fe"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("829269af-7a8c-4b48-bef5-8fcd14b16e39"),
                            BookDefinitionId = new Guid("618a6b7e-93d5-4996-b436-863c09d81da7"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("65d11cff-6a79-44fc-ba05-672f0b767653"),
                            BookDefinitionId = new Guid("618a6b7e-93d5-4996-b436-863c09d81da7"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("f9c49789-ccc4-41ef-96ca-94f139a326d4"),
                            BookDefinitionId = new Guid("13d09eed-4525-494b-a5a7-1d1e8b570358"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("5475f152-71b1-4c78-a6cb-fb87c9f0a97d"),
                            BookDefinitionId = new Guid("e98ff57a-788c-4bff-97f8-49dc00742736"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("0616b6d4-6925-44b0-996d-549d7a268426"),
                            BookDefinitionId = new Guid("78fd8609-958a-404a-8e76-ad9620e6bb03"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("40fc90cb-7ae0-4d7d-a414-50ba37bb8c85"),
                            BookDefinitionId = new Guid("8f4c8b2c-c736-4bed-b288-3c1ae863b84f"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("f4234669-0cf6-497a-ba87-78d3e1d2431b"),
                            BookDefinitionId = new Guid("8f4c8b2c-c736-4bed-b288-3c1ae863b84f"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("46f985c2-c186-492d-ae97-1932a614ba41"),
                            BookDefinitionId = new Guid("c84c9e9c-c249-4225-bb57-24e639f691a4"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("1e613789-2cef-418d-b0c0-2a962d27ed58"),
                            BookDefinitionId = new Guid("8f4c8b2c-c736-4bed-b288-3c1ae863b84f"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("54f7cbec-d698-4135-812b-ebb817d9668b"),
                            BookDefinitionId = new Guid("aa5d87f3-cdc3-4631-a983-4d62834e4fb3"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("3254379f-42df-436b-9361-8dc799b25c22"),
                            BookDefinitionId = new Guid("f1559d9f-ca57-4ebe-994b-3b3313b11f54"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("baf0709f-bf7b-47ac-b3fb-3861138b08b1"),
                            BookDefinitionId = new Guid("78fd8609-958a-404a-8e76-ad9620e6bb03"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("0a94853f-b266-451d-8b34-ba1fb38a5501"),
                            BookDefinitionId = new Guid("13d09eed-4525-494b-a5a7-1d1e8b570358"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("5f983603-10c8-4afe-bd87-0485833bbe84"),
                            BookDefinitionId = new Guid("c84c9e9c-c249-4225-bb57-24e639f691a4"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("3eb520c7-d7da-4555-80bf-ab1b0b4bc4d3"),
                            BookDefinitionId = new Guid("d21ca2bc-1dab-463e-8bb5-1512054a3ba7"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("e84c3c0d-424f-4cac-8787-cfa769a03f4f"),
                            BookDefinitionId = new Guid("d21ca2bc-1dab-463e-8bb5-1512054a3ba7"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("9e6a7ac2-ed88-4935-a52e-bc4e2d8f1891"),
                            BookDefinitionId = new Guid("618a6b7e-93d5-4996-b436-863c09d81da7"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("ca78df1e-8117-4306-8b5d-445034aac1a5"),
                            BookDefinitionId = new Guid("e98ff57a-788c-4bff-97f8-49dc00742736"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("52652373-ba83-447d-b11a-9a8abb4e718d"),
                            BookDefinitionId = new Guid("a4c345ef-03fa-4b77-9387-8e85f8145409"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("5d3e80e1-a3bc-4ccf-82e8-b0d6b8d0ee9e"),
                            BookDefinitionId = new Guid("9b15f13d-4b31-4735-aa18-3fcacfa550fe"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("1b46a3d6-4174-4ab9-9918-0903f963e726"),
                            BookDefinitionId = new Guid("a8e541b1-398f-4f33-8290-bb6130bd81c8"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ef9ab9a5-208f-4792-bfb2-f8f6128727ac"),
                            BookDefinitionId = new Guid("f1559d9f-ca57-4ebe-994b-3b3313b11f54"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("d1189a53-c3b8-473b-aef1-8b5ecd6a2bed"),
                            BookDefinitionId = new Guid("13d09eed-4525-494b-a5a7-1d1e8b570358"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("20a8d076-6834-448f-9e6c-087031ba6d65"),
                            BookDefinitionId = new Guid("13d09eed-4525-494b-a5a7-1d1e8b570358"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("058ec9ab-a8e3-42da-9290-df58faa62a8c"),
                            BookDefinitionId = new Guid("176bb127-2552-47a2-930f-f2ca8ea379f0"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("29fa7e90-1a3b-4344-864a-87e24963b7fc"),
                            BookDefinitionId = new Guid("d21ca2bc-1dab-463e-8bb5-1512054a3ba7"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("9e41c791-55b5-4b9a-8815-1dba31e2bcf0"),
                            BookDefinitionId = new Guid("b6852f11-8ba9-4064-b4d7-10390ae65107"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("64f6c1cf-969c-404d-9156-5cad2e6c8840"),
                            BookDefinitionId = new Guid("dd259cc3-8168-4ad9-a084-96868d2b7aad"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("22aabf87-66a1-4e93-b308-4b5b460861cc"),
                            BookDefinitionId = new Guid("aa5d87f3-cdc3-4631-a983-4d62834e4fb3"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("9a202ac2-6fb9-4dfa-8fd9-3a510570b73b"),
                            BookDefinitionId = new Guid("7cb5de95-bcb7-4b29-a905-a4948f684804"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("731df53e-f4b0-47ac-b077-b3ccd05dbe2a"),
                            BookDefinitionId = new Guid("07913eae-9ea9-4414-8aa2-03095767cf21"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("48390173-b528-4016-a275-24138d338c56"),
                            BookDefinitionId = new Guid("176bb127-2552-47a2-930f-f2ca8ea379f0"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("0d9fa12a-e997-4a19-aeb0-fe7606dda0fe"),
                            BookDefinitionId = new Guid("2d0b7b52-4660-43c5-af33-5e545151d9e1"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("cc0e4979-c57c-4995-a8c9-8f7e8c35fbb3"),
                            BookDefinitionId = new Guid("5390d6ee-4110-4afe-8973-282da308c7e2"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("bcb764da-31ad-42b6-a22b-a1c5c2a1b26d"),
                            BookDefinitionId = new Guid("aa5d87f3-cdc3-4631-a983-4d62834e4fb3"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8ab21a42-fa2f-480e-bd0a-7d304c66db2f"),
                            BookDefinitionId = new Guid("acbe8d8c-0823-467a-9aff-7a5b8ca0176e"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("38be8756-f66e-4174-b1f4-2bbd26a208bd"),
                            BookDefinitionId = new Guid("a4c345ef-03fa-4b77-9387-8e85f8145409"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("f73a96b3-270e-4e47-a86e-58776b7b6c89"),
                            BookDefinitionId = new Guid("176bb127-2552-47a2-930f-f2ca8ea379f0"),
                            Status = 2
                        });
                });

            modelBuilder.Entity("LibSys.Models.Entities.BookDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("07913eae-9ea9-4414-8aa2-03095767cf21"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i Kamień Filozoficzny"
                        },
                        new
                        {
                            Id = new Guid("9b15f13d-4b31-4735-aa18-3fcacfa550fe"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i Komnata Tajemnic"
                        },
                        new
                        {
                            Id = new Guid("5390d6ee-4110-4afe-8973-282da308c7e2"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i więzień Azkabanu"
                        },
                        new
                        {
                            Id = new Guid("655d042a-d318-406a-8412-ab7250c5fcaa"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i Czara Ognia"
                        },
                        new
                        {
                            Id = new Guid("e23a5b30-4b9f-489c-b1ca-d82ec805aace"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i Zakon Feniksa"
                        },
                        new
                        {
                            Id = new Guid("78fd8609-958a-404a-8e76-ad9620e6bb03"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i Książę Półkrwi"
                        },
                        new
                        {
                            Id = new Guid("4e23c486-b467-4454-95b0-cced2943d907"),
                            Author = "Stieg Larsson",
                            Title = "Mężczyźni, którzy nienawidzą kobiet"
                        },
                        new
                        {
                            Id = new Guid("acbe8d8c-0823-467a-9aff-7a5b8ca0176e"),
                            Author = "George R.R. Martin",
                            Title = "Gra o tron (edycja ilustrowana)"
                        },
                        new
                        {
                            Id = new Guid("13d09eed-4525-494b-a5a7-1d1e8b570358"),
                            Author = "William Shakespeare",
                            Title = "Romeo i Julia"
                        },
                        new
                        {
                            Id = new Guid("8f4c8b2c-c736-4bed-b288-3c1ae863b84f"),
                            Author = "George R.R. Martin",
                            Title = "Starcie królów (edycja ilustrowana)"
                        },
                        new
                        {
                            Id = new Guid("53ead14f-b23e-45cc-a972-1dc24e9a3424"),
                            Author = "Camilla Läckberg",
                            Title = "Księżniczka z lodu"
                        },
                        new
                        {
                            Id = new Guid("aa5d87f3-cdc3-4631-a983-4d62834e4fb3"),
                            Author = "George R.R. Martin",
                            Title = "Nawałnica mieczy: Stal i śnieg"
                        },
                        new
                        {
                            Id = new Guid("0c60955d-53e8-4563-8c47-2cc681c72a43"),
                            Author = "Johann Wolfgang von Goethe",
                            Title = "Cierpienia młodego Wertera"
                        },
                        new
                        {
                            Id = new Guid("d5ed9c9a-a30f-43fd-b1ee-eb734c09c63f"),
                            Author = "Veronica Roth",
                            Title = "Niezgodna"
                        },
                        new
                        {
                            Id = new Guid("d21ca2bc-1dab-463e-8bb5-1512054a3ba7"),
                            Author = "J.K. Rowling, Jack Thorne",
                            Title = "Harry Potter i Przeklęte Dziecko"
                        },
                        new
                        {
                            Id = new Guid("612ab7d8-20e7-4200-8412-85b66b15fef0"),
                            Author = "Juliusz Słowacki",
                            Title = "Balladyna"
                        },
                        new
                        {
                            Id = new Guid("618a6b7e-93d5-4996-b436-863c09d81da7"),
                            Author = "Camilla Läckberg",
                            Title = "Kaznodzieja"
                        },
                        new
                        {
                            Id = new Guid("cdf00e59-8e6f-4baf-aacc-c71a1e2bb25a"),
                            Author = "Dan Brown",
                            Title = "Inferno"
                        },
                        new
                        {
                            Id = new Guid("bdad4fb2-d095-498c-8273-fa19ac17d799"),
                            Author = "Stanisław Wyspiański",
                            Title = "Wesele"
                        },
                        new
                        {
                            Id = new Guid("dd259cc3-8168-4ad9-a084-96868d2b7aad"),
                            Author = "Camilla Läckberg",
                            Title = "Kamieniarz"
                        },
                        new
                        {
                            Id = new Guid("2d0b7b52-4660-43c5-af33-5e545151d9e1"),
                            Author = "Jo Nesbø",
                            Title = "Człowiek nietoperz"
                        },
                        new
                        {
                            Id = new Guid("a4c345ef-03fa-4b77-9387-8e85f8145409"),
                            Author = "Juliusz Słowacki",
                            Title = "Kordian"
                        },
                        new
                        {
                            Id = new Guid("e98ff57a-788c-4bff-97f8-49dc00742736"),
                            Author = "Andrzej Sapkowski",
                            Title = "Narrenturm"
                        },
                        new
                        {
                            Id = new Guid("a8e541b1-398f-4f33-8290-bb6130bd81c8"),
                            Author = "Kornel Makuszyński",
                            Title = "Szatan z siódmej klasy"
                        },
                        new
                        {
                            Id = new Guid("f1d275eb-c762-4af8-8148-4f3eaca07b3a"),
                            Author = "Camilla Läckberg",
                            Title = "Ofiara losu"
                        },
                        new
                        {
                            Id = new Guid("c84c9e9c-c249-4225-bb57-24e639f691a4"),
                            Author = "Cassandra Clare",
                            Title = "Miasto upadłych aniołów"
                        },
                        new
                        {
                            Id = new Guid("b6852f11-8ba9-4064-b4d7-10390ae65107"),
                            Author = "Camilla Läckberg",
                            Title = "Niemiecki bękart"
                        },
                        new
                        {
                            Id = new Guid("7cb5de95-bcb7-4b29-a905-a4948f684804"),
                            Author = "Władysław Stanisław Reymont",
                            Title = "Chłopi"
                        },
                        new
                        {
                            Id = new Guid("176bb127-2552-47a2-930f-f2ca8ea379f0"),
                            Author = "Andrzej Ziemiański",
                            Title = "Achaja. Tom I"
                        },
                        new
                        {
                            Id = new Guid("f1559d9f-ca57-4ebe-994b-3b3313b11f54"),
                            Author = "Christopher Paolini",
                            Title = "Dziedzictwo"
                        });
                });

            modelBuilder.Entity("LibSys.Models.Entities.Borrowing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("ReaderId");

                    b.ToTable("Borrowings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("37b73b12-3207-4b65-9482-ca6f550a6a98"),
                            BookId = new Guid("f6fdf555-7445-4a25-8313-d020fc757144"),
                            BorrowDate = new DateTime(2025, 5, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("437b01ab-9a20-4e7b-ae77-2ab47be0d6c5"),
                            ReturnDate = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("b95f2458-58e1-445b-9741-9ef8ef618466"),
                            BookId = new Guid("1243510f-33ad-4cfe-977d-f97096cf7912"),
                            BorrowDate = new DateTime(2025, 5, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("1a19aac1-5f81-4906-9f8b-344b4e7a3908"),
                            BookId = new Guid("7df14d9f-7a50-4c6c-b673-4f37c02b4ea4"),
                            BorrowDate = new DateTime(2025, 5, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("437b01ab-9a20-4e7b-ae77-2ab47be0d6c5"),
                            ReturnDate = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("8a5e9b15-c85d-4dd0-8102-cad9a8f52bd5"),
                            BookId = new Guid("f815c08a-8040-44be-9a6e-a24df7754312"),
                            BorrowDate = new DateTime(2025, 5, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("a044d147-3e3b-45eb-af9f-0a5e16e16e8e"),
                            BookId = new Guid("be89ac0c-e9dc-4f0c-a3db-1ea562385fd4"),
                            BorrowDate = new DateTime(2025, 5, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("785a2929-5604-4245-aa4d-2b7786aeadbd"),
                            ReturnDate = new DateTime(2025, 7, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("45b6e149-169e-4035-892c-14489b598aa3"),
                            BookId = new Guid("0fd2b647-d423-425f-871b-2765fd4af17e"),
                            BorrowDate = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("437b01ab-9a20-4e7b-ae77-2ab47be0d6c5"),
                            ReturnDate = new DateTime(2025, 7, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("649cc5c3-626e-41e8-a21a-beb5452cf0d0"),
                            BookId = new Guid("c708f6d4-ab95-4c05-a0cf-335d140fb7fe"),
                            BorrowDate = new DateTime(2025, 5, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("785a2929-5604-4245-aa4d-2b7786aeadbd"),
                            ReturnDate = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("010619e4-3e12-4797-a996-410e92784d40"),
                            BookId = new Guid("17dd14f0-d15f-42b2-bd2d-8334302f4b45"),
                            BorrowDate = new DateTime(2025, 5, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("4a451efe-7c82-4401-a131-1aae044454f0"),
                            ReturnDate = new DateTime(2025, 7, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("25b76f3d-3a62-4ac1-9e42-aae827c43914"),
                            BookId = new Guid("e5618def-55b6-492a-8799-a308504a858b"),
                            BorrowDate = new DateTime(2025, 5, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("785a2929-5604-4245-aa4d-2b7786aeadbd"),
                            ReturnDate = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("46b68ef5-9b05-459f-9212-d946095eb983"),
                            BookId = new Guid("adcba8af-d725-4ae9-8d03-a1231aa1d260"),
                            BorrowDate = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("4a451efe-7c82-4401-a131-1aae044454f0"),
                            ReturnDate = new DateTime(2025, 7, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("9eb02121-8815-4792-a8b4-727d10bc4843"),
                            BookId = new Guid("d48daad4-7925-4788-83fa-e688c1c2d0a4"),
                            BorrowDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("437b01ab-9a20-4e7b-ae77-2ab47be0d6c5"),
                            ReturnDate = new DateTime(2025, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("139f2b1f-c932-4bf7-a639-5ca19722039f"),
                            BookId = new Guid("2e2a1e35-621a-4181-b898-6a08e9a4e9ad"),
                            BorrowDate = new DateTime(2025, 5, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("4a451efe-7c82-4401-a131-1aae044454f0"),
                            ReturnDate = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("50e0d53e-56d3-47a3-835b-d5e848568d6b"),
                            BookId = new Guid("b21f7b8c-56cc-4d35-a56c-a5ffa91be616"),
                            BorrowDate = new DateTime(2025, 5, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("4a451efe-7c82-4401-a131-1aae044454f0"),
                            ReturnDate = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("eb5099cc-b154-48ac-b912-95dbc5cacc3e"),
                            BookId = new Guid("e77acec1-f669-4c72-87fd-9d103304c1e6"),
                            BorrowDate = new DateTime(2025, 5, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("4a451efe-7c82-4401-a131-1aae044454f0"),
                            ReturnDate = new DateTime(2025, 7, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("2245ba3a-d87c-4695-a171-f779d405a327"),
                            BookId = new Guid("35f4f434-363b-48ef-9bbe-da2104771b4e"),
                            BorrowDate = new DateTime(2025, 5, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("e7398e81-fe00-41bc-bf13-5ee50a44424d"),
                            BookId = new Guid("490d4c28-d160-4985-bbf3-c3dd816e5687"),
                            BorrowDate = new DateTime(2025, 5, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("0ecb38d8-15dc-4354-8455-7cd1c6c13578"),
                            BookId = new Guid("36efaff9-67e1-4a8e-b435-f524a61e21a8"),
                            BorrowDate = new DateTime(2025, 5, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("785a2929-5604-4245-aa4d-2b7786aeadbd"),
                            ReturnDate = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("5ce844bf-c210-4ae5-8173-44ddaa161996"),
                            BookId = new Guid("dcf6a437-a2e9-4f07-8b94-be6f87760c4a"),
                            BorrowDate = new DateTime(2025, 5, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("4a451efe-7c82-4401-a131-1aae044454f0"),
                            ReturnDate = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("5d59f0b4-3a38-4f2b-93d2-a6b722de265b"),
                            BookId = new Guid("9c606f65-4b1f-4c05-a099-a251b81d9f2b"),
                            BorrowDate = new DateTime(2025, 5, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("785a2929-5604-4245-aa4d-2b7786aeadbd"),
                            ReturnDate = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("2a7963ff-ba3c-4779-b297-5f9a3bd8ab5c"),
                            BookId = new Guid("a4498221-c3e0-4141-a23c-254f49a89ebb"),
                            BorrowDate = new DateTime(2025, 5, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("785a2929-5604-4245-aa4d-2b7786aeadbd"),
                            ReturnDate = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("8346f9cb-946a-4132-bf39-d700a55218cf"),
                            BookId = new Guid("829269af-7a8c-4b48-bef5-8fcd14b16e39"),
                            BorrowDate = new DateTime(2025, 5, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("437b01ab-9a20-4e7b-ae77-2ab47be0d6c5"),
                            ReturnDate = new DateTime(2025, 7, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("42584adc-d258-4b32-b1e8-fe244c761537"),
                            BookId = new Guid("0616b6d4-6925-44b0-996d-549d7a268426"),
                            BorrowDate = new DateTime(2025, 5, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("785a2929-5604-4245-aa4d-2b7786aeadbd"),
                            ReturnDate = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("223a9173-a281-48d0-a291-1dc6d955bcec"),
                            BookId = new Guid("0a94853f-b266-451d-8b34-ba1fb38a5501"),
                            BorrowDate = new DateTime(2025, 5, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("785a2929-5604-4245-aa4d-2b7786aeadbd"),
                            ReturnDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("2f10571c-b2f3-4ba0-bcc1-22168899dc94"),
                            BookId = new Guid("9e6a7ac2-ed88-4935-a52e-bc4e2d8f1891"),
                            BorrowDate = new DateTime(2025, 5, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("785a2929-5604-4245-aa4d-2b7786aeadbd"),
                            ReturnDate = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("21059172-d610-4f1d-a450-4ab76c977481"),
                            BookId = new Guid("d1189a53-c3b8-473b-aef1-8b5ecd6a2bed"),
                            BorrowDate = new DateTime(2025, 5, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("437b01ab-9a20-4e7b-ae77-2ab47be0d6c5"),
                            ReturnDate = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("b29a99d7-b642-4d53-b8f5-94fb646a3194"),
                            BookId = new Guid("058ec9ab-a8e3-42da-9290-df58faa62a8c"),
                            BorrowDate = new DateTime(2025, 5, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("4a451efe-7c82-4401-a131-1aae044454f0"),
                            ReturnDate = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("516a3e4d-8a52-48e9-b452-7d84a101afeb"),
                            BookId = new Guid("9a202ac2-6fb9-4dfa-8fd9-3a510570b73b"),
                            BorrowDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2025, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("LibSys.Models.Entities.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityChanges")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MethodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("LibSys.Models.Entities.Reader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Readers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            City = "Poznań",
                            Code = "61-842",
                            Name = "Jan Kowalski",
                            Street = "Za Bramką 12"
                        },
                        new
                        {
                            Id = new Guid("437b01ab-9a20-4e7b-ae77-2ab47be0d6c5"),
                            City = "Poznań",
                            Code = "61-111",
                            Name = "Tomasz Rydz",
                            Street = "Garbary 1"
                        },
                        new
                        {
                            Id = new Guid("4a451efe-7c82-4401-a131-1aae044454f0"),
                            City = "Poznań",
                            Code = "61-111",
                            Name = "Aleksandra Mechrzycka",
                            Street = "Solna 2"
                        },
                        new
                        {
                            Id = new Guid("785a2929-5604-4245-aa4d-2b7786aeadbd"),
                            City = "Poznań",
                            Code = "61-311",
                            Name = "Jan Nowak",
                            Street = "Wieżowa 3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8398a233-f6b9-4361-977c-da6a3e9c2bbe",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "6413944e-a5d8-430e-9a85-a914f5cb349b",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b74ddd14-6340-4840-95c2-db12554843e5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e729fae3-57e5-49eb-b51d-74be9d42544f",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHRoMPCRVXOJPa+QZZXfG7e4V9uxXCiP7m6949FC8EPYvExRD0P2/3wxIVu9BZ/TIQ==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "811c060f-3b61-4f57-b05c-3ddd89e4a152",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "b74ddd14-6340-4840-95c2-db12554843e5",
                            RoleId = "8398a233-f6b9-4361-977c-da6a3e9c2bbe"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LibSys.Models.Entities.Book", b =>
                {
                    b.HasOne("LibSys.Models.Entities.BookDefinition", "BookDefinition")
                        .WithMany()
                        .HasForeignKey("BookDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookDefinition");
                });

            modelBuilder.Entity("LibSys.Models.Entities.Borrowing", b =>
                {
                    b.HasOne("LibSys.Models.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibSys.Models.Entities.Reader", "Reader")
                        .WithMany()
                        .HasForeignKey("ReaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("LibSys.Models.Entities.Reader", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
