// <auto-generated />
using System;
using LibSys.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibSys.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250529072837_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibSys.Models.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookDefinitionId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("740ff527-8fe4-42e2-a1c6-8760934ba25c"),
                            BookDefinitionId = new Guid("2e5348d6-5033-45ce-99ca-1246864751d5"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("a8344ecf-a6b7-44b6-968f-3be73b62bfcf"),
                            BookDefinitionId = new Guid("bef8a1e0-6b79-4baa-87f9-b2d0ded980dc"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("a3c52fd3-1622-4761-ad7a-b87ab4d693d8"),
                            BookDefinitionId = new Guid("69adfa84-daf3-4a3d-8ad5-53daaa26ce96"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("e0557675-d411-4161-b28e-05e14d61bb76"),
                            BookDefinitionId = new Guid("6508fcf2-37a6-40ee-a0eb-422586cb27b8"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("683b8066-c9ad-4f48-b19d-40f240a455a7"),
                            BookDefinitionId = new Guid("0d8b13ce-c312-4ab6-ade1-9f520572d3d1"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("1d761150-d68e-4a7d-b1eb-527a83369f41"),
                            BookDefinitionId = new Guid("9a61fa0e-cad5-4e65-b1e2-51f17e290a35"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("944164c6-b86f-41b7-97d6-f743c2b92443"),
                            BookDefinitionId = new Guid("6dcdd6ed-f35c-4c82-8c28-79d2a9fece96"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("22299b68-0f32-4a1f-98b3-fdca4e2cab03"),
                            BookDefinitionId = new Guid("ef875e6c-d757-4174-b6d0-943e91a54ea6"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("04409baa-150f-41c7-a377-0b4604feb78b"),
                            BookDefinitionId = new Guid("0d8b13ce-c312-4ab6-ade1-9f520572d3d1"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("4fa6c3f0-8eb8-4fea-87e9-a6e254a0c7b9"),
                            BookDefinitionId = new Guid("aaaf05df-6fae-4cdd-baff-41227de9ff81"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("d09c1bde-86f3-4729-9fda-b2d32ea4f432"),
                            BookDefinitionId = new Guid("d23360a4-e749-4ead-beb2-cacabac0a81b"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("32d08c81-aa38-48a0-94ec-f6627d14fc1c"),
                            BookDefinitionId = new Guid("7d7b843f-53e7-411e-a59d-0e4e8a189187"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("5b3707b6-6f4e-4b28-8625-7bbd3c7e35d2"),
                            BookDefinitionId = new Guid("cde5099d-5d2f-40ee-b3d4-6f114e60d6a0"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("b5e332e8-5f46-4e25-8fb4-73a3d61d6782"),
                            BookDefinitionId = new Guid("9dd9f9cf-858a-4520-b138-ed6f59fb9ca2"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("68da4603-2f36-49bf-aef2-6d5620877571"),
                            BookDefinitionId = new Guid("4b2f9ce6-73b3-4140-ae76-dfce880a9ff6"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b8a0724b-9651-4ac7-9eee-f46e30b14850"),
                            BookDefinitionId = new Guid("ef875e6c-d757-4174-b6d0-943e91a54ea6"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("2d3287f3-fdf1-4e70-b2f6-3c7efec08de4"),
                            BookDefinitionId = new Guid("0f0d814a-3f87-44f5-9cec-0b7ea94fb457"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("1bcbf03f-169b-4e00-8fe0-eb4ed205460f"),
                            BookDefinitionId = new Guid("ef2c01fd-4e66-4f31-831d-2114abd85173"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("bcee4c61-51c3-49a8-ac8e-03dd5f970ec8"),
                            BookDefinitionId = new Guid("5c836eab-abf2-4621-8d62-3094a83a685c"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("4e651f9f-8820-4fd2-afb8-1379b242d797"),
                            BookDefinitionId = new Guid("5c836eab-abf2-4621-8d62-3094a83a685c"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("4cd7e92e-1fd6-4ff1-8751-41b42fd499b9"),
                            BookDefinitionId = new Guid("096e7f43-42f7-4aec-aae5-8150ca544988"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("1888c887-81e1-4046-b280-72baa3d22ec7"),
                            BookDefinitionId = new Guid("6dcdd6ed-f35c-4c82-8c28-79d2a9fece96"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("f47d6cda-94f8-49f5-a3ea-c060e1a9a4b8"),
                            BookDefinitionId = new Guid("69adfa84-daf3-4a3d-8ad5-53daaa26ce96"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("ddc34418-4987-45c2-a064-f377ccde17f0"),
                            BookDefinitionId = new Guid("aaaf05df-6fae-4cdd-baff-41227de9ff81"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("e5e9745c-aaa6-445e-abab-3a1e6fc37d72"),
                            BookDefinitionId = new Guid("618e06c4-a6f5-42fd-85fa-6b1473fc7220"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("959ce6b3-9571-46b3-9353-c260f856b049"),
                            BookDefinitionId = new Guid("9a61fa0e-cad5-4e65-b1e2-51f17e290a35"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("bb1ab2a2-abf2-459e-814b-e6a828db882a"),
                            BookDefinitionId = new Guid("b1af4309-530b-4dbd-8d3b-5a6918951efa"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("0153d434-ef3a-40f1-8533-907dec68d164"),
                            BookDefinitionId = new Guid("20681464-4c2f-48e9-8298-1963d0ac0deb"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("22f2196a-e666-43f4-856c-f79f566b3347"),
                            BookDefinitionId = new Guid("5c836eab-abf2-4621-8d62-3094a83a685c"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("488f3e25-4c93-4c73-8936-0e9fe2293ec6"),
                            BookDefinitionId = new Guid("cb4a428b-6ebb-420e-aa6c-605a3e5de5a1"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("d962a2bc-7dc6-431c-a778-0aa2853ce979"),
                            BookDefinitionId = new Guid("69adfa84-daf3-4a3d-8ad5-53daaa26ce96"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("5d1d6d82-9e97-486f-a4f0-9bb2eed129ad"),
                            BookDefinitionId = new Guid("6508fcf2-37a6-40ee-a0eb-422586cb27b8"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("2959712c-0ae7-4625-9773-0c08deadd084"),
                            BookDefinitionId = new Guid("7d7b843f-53e7-411e-a59d-0e4e8a189187"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("1c283061-3f71-4237-993d-cade422877ed"),
                            BookDefinitionId = new Guid("5c836eab-abf2-4621-8d62-3094a83a685c"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("de13e8a3-2d58-45f5-baa4-ffccbb8f11d8"),
                            BookDefinitionId = new Guid("0f0d814a-3f87-44f5-9cec-0b7ea94fb457"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d1caa2a1-c28d-486d-95bf-0a4bf9ac1cbb"),
                            BookDefinitionId = new Guid("aaaf05df-6fae-4cdd-baff-41227de9ff81"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("527a3be6-1539-4522-9a4a-ab43cc9785d8"),
                            BookDefinitionId = new Guid("ef2c01fd-4e66-4f31-831d-2114abd85173"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("5f49739f-50cf-479a-a1f5-03b1ee1d4d0b"),
                            BookDefinitionId = new Guid("69adfa84-daf3-4a3d-8ad5-53daaa26ce96"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("97072cef-9bcd-4265-ba30-0a0fd78c6436"),
                            BookDefinitionId = new Guid("7d7b843f-53e7-411e-a59d-0e4e8a189187"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a5545a5d-c0ba-4018-8a7f-ef2171d3bd19"),
                            BookDefinitionId = new Guid("b1af4309-530b-4dbd-8d3b-5a6918951efa"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("fad1f62a-68a2-4d53-b70a-5af8a6d2640b"),
                            BookDefinitionId = new Guid("8c1dfd9f-da3e-4acf-be48-4dc6b1802c79"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("2a6e605b-1265-4720-8f70-81e1dae8825c"),
                            BookDefinitionId = new Guid("86aa59e9-6e57-4a28-a688-dc2aa2c3b0e1"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("2eb9569f-751b-4d04-b3cd-aa24d5584d90"),
                            BookDefinitionId = new Guid("6dae31df-8169-418a-aa5d-0877064a1df0"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("a0c9f9d3-8915-41ab-a47c-c951f9c330ec"),
                            BookDefinitionId = new Guid("4b2f9ce6-73b3-4140-ae76-dfce880a9ff6"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("98b492ed-d956-4d8c-9ad3-c3e2181d9f97"),
                            BookDefinitionId = new Guid("2e5348d6-5033-45ce-99ca-1246864751d5"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("fe176798-19cb-4e13-81a0-4ca6336e8aa5"),
                            BookDefinitionId = new Guid("6dcdd6ed-f35c-4c82-8c28-79d2a9fece96"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("d83738fa-2dff-430d-b6b2-4e4444f15ab2"),
                            BookDefinitionId = new Guid("ef875e6c-d757-4174-b6d0-943e91a54ea6"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("e91e0c01-65f6-4aef-b2e0-c0e3522d6290"),
                            BookDefinitionId = new Guid("8d717003-7ef7-4a4b-9e12-d5e7901873c3"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("da3e3e65-83b8-4cee-95f3-429e6a5c5c3d"),
                            BookDefinitionId = new Guid("aaaf05df-6fae-4cdd-baff-41227de9ff81"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("78ac340c-2c1b-45e6-80be-0e38a450adcf"),
                            BookDefinitionId = new Guid("0f0d814a-3f87-44f5-9cec-0b7ea94fb457"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("76abbd49-55ef-4c31-8d72-9e95244b699d"),
                            BookDefinitionId = new Guid("0d8b13ce-c312-4ab6-ade1-9f520572d3d1"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b1987401-f716-4f7a-8435-c677e29d8f4b"),
                            BookDefinitionId = new Guid("ef875e6c-d757-4174-b6d0-943e91a54ea6"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("809163f6-0376-4882-bf72-8af1c3a28a53"),
                            BookDefinitionId = new Guid("aaaf05df-6fae-4cdd-baff-41227de9ff81"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("0dd4f40d-7d4d-4c48-8f76-6617c06837af"),
                            BookDefinitionId = new Guid("4b2f9ce6-73b3-4140-ae76-dfce880a9ff6"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("ea14453c-9f94-4d0e-9b93-b2f5b9dbc8c2"),
                            BookDefinitionId = new Guid("0d8b13ce-c312-4ab6-ade1-9f520572d3d1"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("f1bd67fb-6ff2-47bf-a685-e6585ed593c2"),
                            BookDefinitionId = new Guid("c79cb02b-2097-4c64-a9eb-2d953622afaf"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("c28fdcfc-328c-4724-9eaf-6b5e094c12e7"),
                            BookDefinitionId = new Guid("7d7b843f-53e7-411e-a59d-0e4e8a189187"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("a5bd34c9-cad1-4cdd-8d4b-81bda92ec2c8"),
                            BookDefinitionId = new Guid("0d8b13ce-c312-4ab6-ade1-9f520572d3d1"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("f0c9f6e4-2800-4bf0-9a13-a53462881f7f"),
                            BookDefinitionId = new Guid("2e5348d6-5033-45ce-99ca-1246864751d5"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("c39a4265-485c-45c5-ab7b-1dadb839c19f"),
                            BookDefinitionId = new Guid("c79cb02b-2097-4c64-a9eb-2d953622afaf"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8f68c8c3-f03d-4d84-9e66-a7be4283601f"),
                            BookDefinitionId = new Guid("b1af4309-530b-4dbd-8d3b-5a6918951efa"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("1b54954e-a65f-4b3e-a055-e512a94ba937"),
                            BookDefinitionId = new Guid("bef8a1e0-6b79-4baa-87f9-b2d0ded980dc"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("596dbd64-2d93-40b0-91a6-e8b55618b979"),
                            BookDefinitionId = new Guid("0d8b13ce-c312-4ab6-ade1-9f520572d3d1"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("a6a6d974-5335-43d8-82dc-ddd5569ef9bd"),
                            BookDefinitionId = new Guid("6dcdd6ed-f35c-4c82-8c28-79d2a9fece96"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("a5f89727-f36d-493b-b8a6-1107ea9bbaa8"),
                            BookDefinitionId = new Guid("ef2c01fd-4e66-4f31-831d-2114abd85173"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("0f270e07-4c82-4b53-bc0d-44e5c4a0f65e"),
                            BookDefinitionId = new Guid("4b2f9ce6-73b3-4140-ae76-dfce880a9ff6"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("87ea4b18-ae43-4df2-988e-0475c640b174"),
                            BookDefinitionId = new Guid("9a61fa0e-cad5-4e65-b1e2-51f17e290a35"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("7645beea-eefa-482a-9661-b3a272029161"),
                            BookDefinitionId = new Guid("6dcdd6ed-f35c-4c82-8c28-79d2a9fece96"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("5711f618-c111-447c-a0ec-2e2c47de3f5c"),
                            BookDefinitionId = new Guid("8d717003-7ef7-4a4b-9e12-d5e7901873c3"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("383d9f77-1527-4a84-9c33-7f8d034c70e7"),
                            BookDefinitionId = new Guid("9b10a2bc-ae1e-4650-9731-b4227d89a109"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("1efc4ca5-f1b4-480e-9609-8288fd159293"),
                            BookDefinitionId = new Guid("69adfa84-daf3-4a3d-8ad5-53daaa26ce96"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("224feaff-43f4-4366-975b-75c2d689a76f"),
                            BookDefinitionId = new Guid("7d7b843f-53e7-411e-a59d-0e4e8a189187"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("3a35d4f1-ea6a-47fb-bb07-9bc87cc47df5"),
                            BookDefinitionId = new Guid("5c836eab-abf2-4621-8d62-3094a83a685c"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("e5331303-2952-42e5-960f-47a82e32c697"),
                            BookDefinitionId = new Guid("4b2f9ce6-73b3-4140-ae76-dfce880a9ff6"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("ba5bd906-a9ed-49eb-bd7a-f914e9f36226"),
                            BookDefinitionId = new Guid("d23360a4-e749-4ead-beb2-cacabac0a81b"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("418d1f60-40b6-4ca7-9beb-83efdf647117"),
                            BookDefinitionId = new Guid("b1af4309-530b-4dbd-8d3b-5a6918951efa"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b6d81bdc-ec66-408b-bf17-bab396968af8"),
                            BookDefinitionId = new Guid("2e5348d6-5033-45ce-99ca-1246864751d5"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("59dec810-5a4e-481e-b6d8-1e4e979f6d82"),
                            BookDefinitionId = new Guid("cde5099d-5d2f-40ee-b3d4-6f114e60d6a0"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("0b95f4be-e662-4bdf-b2d4-6b0f4afd8764"),
                            BookDefinitionId = new Guid("20681464-4c2f-48e9-8298-1963d0ac0deb"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("87a00a22-42fa-4c40-93e3-6ef37ffa757f"),
                            BookDefinitionId = new Guid("20681464-4c2f-48e9-8298-1963d0ac0deb"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("5434d5f9-59e9-45ae-b60e-def591915f9e"),
                            BookDefinitionId = new Guid("4b2f9ce6-73b3-4140-ae76-dfce880a9ff6"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("36740fc1-c198-4283-b984-42bb905a8a8e"),
                            BookDefinitionId = new Guid("9b10a2bc-ae1e-4650-9731-b4227d89a109"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("4648f33e-c68c-4a9a-894b-e00a81ef5244"),
                            BookDefinitionId = new Guid("0f0d814a-3f87-44f5-9cec-0b7ea94fb457"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("9e8d0c3a-4988-4b86-8da6-0ef8d84df9cd"),
                            BookDefinitionId = new Guid("6dae31df-8169-418a-aa5d-0877064a1df0"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("9d50d65d-dec7-4409-8991-a0472acd68b9"),
                            BookDefinitionId = new Guid("20681464-4c2f-48e9-8298-1963d0ac0deb"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("7304d5b9-1639-4103-9e30-a091284be2c9"),
                            BookDefinitionId = new Guid("8d717003-7ef7-4a4b-9e12-d5e7901873c3"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("edc5d704-e409-4610-b79e-e69136e325d8"),
                            BookDefinitionId = new Guid("b1af4309-530b-4dbd-8d3b-5a6918951efa"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("e9e5fd26-1c25-40ef-a676-5e23456f187f"),
                            BookDefinitionId = new Guid("9dd9f9cf-858a-4520-b138-ed6f59fb9ca2"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a8281dc2-5a2e-4ef9-a8b1-be6f197e59f0"),
                            BookDefinitionId = new Guid("6dae31df-8169-418a-aa5d-0877064a1df0"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("2155809f-8d7b-4b54-b718-f24d0ab3ddec"),
                            BookDefinitionId = new Guid("0f0d814a-3f87-44f5-9cec-0b7ea94fb457"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("e0824375-1ad0-4a96-9dac-a71c7017773d"),
                            BookDefinitionId = new Guid("8c1dfd9f-da3e-4acf-be48-4dc6b1802c79"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("7aacb625-7458-4cac-9e19-a29285fbe3b2"),
                            BookDefinitionId = new Guid("0d8b13ce-c312-4ab6-ade1-9f520572d3d1"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("f16077b4-f607-4fd0-9c39-4c0af2282777"),
                            BookDefinitionId = new Guid("4b2f9ce6-73b3-4140-ae76-dfce880a9ff6"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("2a534249-c38d-4280-8068-2102b4124406"),
                            BookDefinitionId = new Guid("6dcdd6ed-f35c-4c82-8c28-79d2a9fece96"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a91c046b-d7f9-4a3f-b79f-240a298762e9"),
                            BookDefinitionId = new Guid("6dcdd6ed-f35c-4c82-8c28-79d2a9fece96"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("cb801696-263e-4740-957a-ce024c27b4cf"),
                            BookDefinitionId = new Guid("618e06c4-a6f5-42fd-85fa-6b1473fc7220"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("78adbbff-4fd8-4fa6-be31-205035e14026"),
                            BookDefinitionId = new Guid("d23360a4-e749-4ead-beb2-cacabac0a81b"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("40c74e46-0181-4ea4-b928-2ed3440ff77e"),
                            BookDefinitionId = new Guid("6dcdd6ed-f35c-4c82-8c28-79d2a9fece96"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("5efba376-cc0b-4eb4-b5e6-705c7c5aa3d2"),
                            BookDefinitionId = new Guid("0f0d814a-3f87-44f5-9cec-0b7ea94fb457"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("1f36fe2f-3e7b-48d0-b3cb-836839b2f753"),
                            BookDefinitionId = new Guid("0d8b13ce-c312-4ab6-ade1-9f520572d3d1"),
                            Status = 2
                        });
                });

            modelBuilder.Entity("LibSys.Models.Entities.BookDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bef8a1e0-6b79-4baa-87f9-b2d0ded980dc"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i Kamień Filozoficzny"
                        },
                        new
                        {
                            Id = new Guid("aaaf05df-6fae-4cdd-baff-41227de9ff81"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i Komnata Tajemnic"
                        },
                        new
                        {
                            Id = new Guid("2e5348d6-5033-45ce-99ca-1246864751d5"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i więzień Azkabanu"
                        },
                        new
                        {
                            Id = new Guid("618e06c4-a6f5-42fd-85fa-6b1473fc7220"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i Czara Ognia"
                        },
                        new
                        {
                            Id = new Guid("bd510fa3-a160-4fe8-9821-8f987c68bebc"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i Zakon Feniksa"
                        },
                        new
                        {
                            Id = new Guid("c79cb02b-2097-4c64-a9eb-2d953622afaf"),
                            Author = "J.K. Rowling",
                            Title = "Harry Potter i Książę Półkrwi"
                        },
                        new
                        {
                            Id = new Guid("7d7b843f-53e7-411e-a59d-0e4e8a189187"),
                            Author = "Stieg Larsson",
                            Title = "Mężczyźni, którzy nienawidzą kobiet"
                        },
                        new
                        {
                            Id = new Guid("20681464-4c2f-48e9-8298-1963d0ac0deb"),
                            Author = "George R.R. Martin",
                            Title = "Gra o tron (edycja ilustrowana)"
                        },
                        new
                        {
                            Id = new Guid("6508fcf2-37a6-40ee-a0eb-422586cb27b8"),
                            Author = "William Shakespeare",
                            Title = "Romeo i Julia"
                        },
                        new
                        {
                            Id = new Guid("6dcdd6ed-f35c-4c82-8c28-79d2a9fece96"),
                            Author = "George R.R. Martin",
                            Title = "Starcie królów (edycja ilustrowana)"
                        },
                        new
                        {
                            Id = new Guid("8c1dfd9f-da3e-4acf-be48-4dc6b1802c79"),
                            Author = "Camilla Läckberg",
                            Title = "Księżniczka z lodu"
                        },
                        new
                        {
                            Id = new Guid("6dae31df-8169-418a-aa5d-0877064a1df0"),
                            Author = "George R.R. Martin",
                            Title = "Nawałnica mieczy: Stal i śnieg"
                        },
                        new
                        {
                            Id = new Guid("9dd9f9cf-858a-4520-b138-ed6f59fb9ca2"),
                            Author = "Johann Wolfgang von Goethe",
                            Title = "Cierpienia młodego Wertera"
                        },
                        new
                        {
                            Id = new Guid("0f0d814a-3f87-44f5-9cec-0b7ea94fb457"),
                            Author = "Veronica Roth",
                            Title = "Niezgodna"
                        },
                        new
                        {
                            Id = new Guid("9a61fa0e-cad5-4e65-b1e2-51f17e290a35"),
                            Author = "J.K. Rowling, Jack Thorne",
                            Title = "Harry Potter i Przeklęte Dziecko"
                        },
                        new
                        {
                            Id = new Guid("cb4a428b-6ebb-420e-aa6c-605a3e5de5a1"),
                            Author = "Juliusz Słowacki",
                            Title = "Balladyna"
                        },
                        new
                        {
                            Id = new Guid("9b10a2bc-ae1e-4650-9731-b4227d89a109"),
                            Author = "Camilla Läckberg",
                            Title = "Kaznodzieja"
                        },
                        new
                        {
                            Id = new Guid("cde5099d-5d2f-40ee-b3d4-6f114e60d6a0"),
                            Author = "Dan Brown",
                            Title = "Inferno"
                        },
                        new
                        {
                            Id = new Guid("8d717003-7ef7-4a4b-9e12-d5e7901873c3"),
                            Author = "Stanisław Wyspiański",
                            Title = "Wesele"
                        },
                        new
                        {
                            Id = new Guid("69adfa84-daf3-4a3d-8ad5-53daaa26ce96"),
                            Author = "Camilla Läckberg",
                            Title = "Kamieniarz"
                        },
                        new
                        {
                            Id = new Guid("ef875e6c-d757-4174-b6d0-943e91a54ea6"),
                            Author = "Jo Nesbø",
                            Title = "Człowiek nietoperz"
                        },
                        new
                        {
                            Id = new Guid("5c836eab-abf2-4621-8d62-3094a83a685c"),
                            Author = "Juliusz Słowacki",
                            Title = "Kordian"
                        },
                        new
                        {
                            Id = new Guid("a9631293-7513-495b-a785-f0365a635d88"),
                            Author = "Andrzej Sapkowski",
                            Title = "Narrenturm"
                        },
                        new
                        {
                            Id = new Guid("096e7f43-42f7-4aec-aae5-8150ca544988"),
                            Author = "Kornel Makuszyński",
                            Title = "Szatan z siódmej klasy"
                        },
                        new
                        {
                            Id = new Guid("d23360a4-e749-4ead-beb2-cacabac0a81b"),
                            Author = "Camilla Läckberg",
                            Title = "Ofiara losu"
                        },
                        new
                        {
                            Id = new Guid("4b2f9ce6-73b3-4140-ae76-dfce880a9ff6"),
                            Author = "Cassandra Clare",
                            Title = "Miasto upadłych aniołów"
                        },
                        new
                        {
                            Id = new Guid("ef2c01fd-4e66-4f31-831d-2114abd85173"),
                            Author = "Camilla Läckberg",
                            Title = "Niemiecki bękart"
                        },
                        new
                        {
                            Id = new Guid("b1af4309-530b-4dbd-8d3b-5a6918951efa"),
                            Author = "Władysław Stanisław Reymont",
                            Title = "Chłopi"
                        },
                        new
                        {
                            Id = new Guid("86aa59e9-6e57-4a28-a688-dc2aa2c3b0e1"),
                            Author = "Andrzej Ziemiański",
                            Title = "Achaja. Tom I"
                        },
                        new
                        {
                            Id = new Guid("0d8b13ce-c312-4ab6-ade1-9f520572d3d1"),
                            Author = "Christopher Paolini",
                            Title = "Dziedzictwo"
                        });
                });

            modelBuilder.Entity("LibSys.Models.Entities.Borrowing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("ReaderId");

                    b.ToTable("Borrowings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("408fc73b-ecf0-48aa-9f6e-2a71d8eb2978"),
                            BookId = new Guid("740ff527-8fe4-42e2-a1c6-8760934ba25c"),
                            BorrowDate = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("1957e470-5e20-46ed-9a4d-82ee39ec754e"),
                            ReturnDate = new DateTime(2025, 7, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("f862bbc9-55b5-4182-bda9-f3b48e087da1"),
                            BookId = new Guid("1d761150-d68e-4a7d-b1eb-527a83369f41"),
                            BorrowDate = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("157f19f0-a66e-4161-b899-1ba14953519d"),
                            ReturnDate = new DateTime(2025, 7, 13, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("2423e7e9-292e-48ce-8d52-b87d32c4e4ce"),
                            BookId = new Guid("5b3707b6-6f4e-4b28-8625-7bbd3c7e35d2"),
                            BorrowDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("6a2327b1-852d-441c-a3e6-95319def4f8f"),
                            ReturnDate = new DateTime(2025, 7, 6, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("f1d740ce-d4aa-4275-940d-9ce6ada615e5"),
                            BookId = new Guid("b5e332e8-5f46-4e25-8fb4-73a3d61d6782"),
                            BorrowDate = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("157f19f0-a66e-4161-b899-1ba14953519d"),
                            ReturnDate = new DateTime(2025, 6, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("b7cfbb28-08f0-4170-823a-046e37875bbe"),
                            BookId = new Guid("4cd7e92e-1fd6-4ff1-8751-41b42fd499b9"),
                            BorrowDate = new DateTime(2025, 5, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2025, 7, 12, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("dbb39616-aeb6-455c-83c2-8df7202f9a9a"),
                            BookId = new Guid("f47d6cda-94f8-49f5-a3ea-c060e1a9a4b8"),
                            BorrowDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("1957e470-5e20-46ed-9a4d-82ee39ec754e"),
                            ReturnDate = new DateTime(2025, 7, 11, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("d1263a07-dec9-4991-884d-5bb442d90bfa"),
                            BookId = new Guid("ddc34418-4987-45c2-a064-f377ccde17f0"),
                            BorrowDate = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("1957e470-5e20-46ed-9a4d-82ee39ec754e"),
                            ReturnDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("bc29121f-7542-4ac3-a877-2c1b15007430"),
                            BookId = new Guid("e5e9745c-aaa6-445e-abab-3a1e6fc37d72"),
                            BorrowDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("1957e470-5e20-46ed-9a4d-82ee39ec754e"),
                            ReturnDate = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("05b4f074-d43b-44c4-bfed-a35ad8d64470"),
                            BookId = new Guid("488f3e25-4c93-4c73-8936-0e9fe2293ec6"),
                            BorrowDate = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("1957e470-5e20-46ed-9a4d-82ee39ec754e"),
                            ReturnDate = new DateTime(2025, 6, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("48126097-ab80-4606-9f3a-b3e1c4a09bb2"),
                            BookId = new Guid("5d1d6d82-9e97-486f-a4f0-9bb2eed129ad"),
                            BorrowDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2025, 7, 6, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("91fd4ad7-ff72-49e8-91bc-2593b99f3017"),
                            BookId = new Guid("d1caa2a1-c28d-486d-95bf-0a4bf9ac1cbb"),
                            BorrowDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("6a2327b1-852d-441c-a3e6-95319def4f8f"),
                            ReturnDate = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("37aecbef-1ece-4ad2-b02f-4deb3e7672b1"),
                            BookId = new Guid("2eb9569f-751b-4d04-b3cd-aa24d5584d90"),
                            BorrowDate = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("6a2327b1-852d-441c-a3e6-95319def4f8f"),
                            ReturnDate = new DateTime(2025, 7, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("5f2b17b0-42d8-4168-a87b-619263f7f381"),
                            BookId = new Guid("d83738fa-2dff-430d-b6b2-4e4444f15ab2"),
                            BorrowDate = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("157f19f0-a66e-4161-b899-1ba14953519d"),
                            ReturnDate = new DateTime(2025, 7, 7, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("ef0482f7-e1fc-46cf-914d-63e4ab6aa375"),
                            BookId = new Guid("e91e0c01-65f6-4aef-b2e0-c0e3522d6290"),
                            BorrowDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("ed0d3401-202a-4573-8102-b8da6a560f44"),
                            BookId = new Guid("f0c9f6e4-2800-4bf0-9a13-a53462881f7f"),
                            BorrowDate = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("6a2327b1-852d-441c-a3e6-95319def4f8f"),
                            ReturnDate = new DateTime(2025, 6, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("aef1dca7-5428-4bcd-b774-3a7efd0d0851"),
                            BookId = new Guid("a5f89727-f36d-493b-b8a6-1107ea9bbaa8"),
                            BorrowDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("6a2327b1-852d-441c-a3e6-95319def4f8f"),
                            ReturnDate = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("ef595e45-f755-4aaa-8b3d-a662cd059bc9"),
                            BookId = new Guid("0f270e07-4c82-4b53-bc0d-44e5c4a0f65e"),
                            BorrowDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("157f19f0-a66e-4161-b899-1ba14953519d"),
                            ReturnDate = new DateTime(2025, 7, 11, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("ec2fc5b0-177a-4453-9e36-95836dedcc01"),
                            BookId = new Guid("5711f618-c111-447c-a0ec-2e2c47de3f5c"),
                            BorrowDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("6a2327b1-852d-441c-a3e6-95319def4f8f"),
                            ReturnDate = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("da2dbd96-59ef-47a8-8fc1-a881cc999e88"),
                            BookId = new Guid("383d9f77-1527-4a84-9c33-7f8d034c70e7"),
                            BorrowDate = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("1957e470-5e20-46ed-9a4d-82ee39ec754e"),
                            ReturnDate = new DateTime(2025, 7, 13, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("5a1830fd-9167-4069-98c9-1a633fa72ca1"),
                            BookId = new Guid("224feaff-43f4-4366-975b-75c2d689a76f"),
                            BorrowDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("1957e470-5e20-46ed-9a4d-82ee39ec754e"),
                            ReturnDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("cc6e68ad-9c4a-4627-888e-c271aabadbb4"),
                            BookId = new Guid("3a35d4f1-ea6a-47fb-bb07-9bc87cc47df5"),
                            BorrowDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("157f19f0-a66e-4161-b899-1ba14953519d"),
                            ReturnDate = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("91b18133-9de1-4b7c-9e89-973016d5c9d4"),
                            BookId = new Guid("ba5bd906-a9ed-49eb-bd7a-f914e9f36226"),
                            BorrowDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("157f19f0-a66e-4161-b899-1ba14953519d"),
                            ReturnDate = new DateTime(2025, 7, 2, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("1aa231bd-a902-43e9-9858-28111ff56ccb"),
                            BookId = new Guid("4648f33e-c68c-4a9a-894b-e00a81ef5244"),
                            BorrowDate = new DateTime(2025, 5, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2025, 7, 12, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("0a0fb03a-f762-472f-9741-714cc55d5911"),
                            BookId = new Guid("7aacb625-7458-4cac-9e19-a29285fbe3b2"),
                            BorrowDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("6a2327b1-852d-441c-a3e6-95319def4f8f"),
                            ReturnDate = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("59ff84ab-a5e5-4086-bbda-4b20c6723c48"),
                            BookId = new Guid("a91c046b-d7f9-4a3f-b79f-240a298762e9"),
                            BorrowDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2025, 7, 2, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("726a1619-a8e7-4c2e-9482-db30c0cb9390"),
                            BookId = new Guid("78adbbff-4fd8-4fa6-be31-205035e14026"),
                            BorrowDate = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            ReturnDate = new DateTime(2025, 6, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("2803211d-ad45-4e57-aa5a-b61f54dc2e29"),
                            BookId = new Guid("40c74e46-0181-4ea4-b928-2ed3440ff77e"),
                            BorrowDate = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            ReaderId = new Guid("1957e470-5e20-46ed-9a4d-82ee39ec754e"),
                            ReturnDate = new DateTime(2025, 7, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("LibSys.Models.Entities.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityChanges")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MethodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("LibSys.Models.Entities.Reader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Readers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d31a024-4e84-4f5e-b86b-04b10d79559e"),
                            City = "Poznań",
                            Code = "61-842",
                            Name = "Jan Kowalski",
                            Street = "Za Bramką 12"
                        },
                        new
                        {
                            Id = new Guid("157f19f0-a66e-4161-b899-1ba14953519d"),
                            City = "Poznań",
                            Code = "61-111",
                            Name = "Tomasz Rydz",
                            Street = "Garbary 1"
                        },
                        new
                        {
                            Id = new Guid("6a2327b1-852d-441c-a3e6-95319def4f8f"),
                            City = "Poznań",
                            Code = "61-111",
                            Name = "Aleksandra Mechrzycka",
                            Street = "Solna 2"
                        },
                        new
                        {
                            Id = new Guid("1957e470-5e20-46ed-9a4d-82ee39ec754e"),
                            City = "Poznań",
                            Code = "61-311",
                            Name = "Jan Nowak",
                            Street = "Wieżowa 3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8398a233-f6b9-4361-977c-da6a3e9c2bbe",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "6413944e-a5d8-430e-9a85-a914f5cb349b",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b74ddd14-6340-4840-95c2-db12554843e5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6fd0e1df-4e35-4be3-b3c3-26458c110627",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEANbQ9kDKh7gcbF5PxJpe5rI1mwgNmc26iF1O2zEKBz7+Ira2EstsBT1Zbbii73nCA==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "080e05f5-060a-460d-a424-d8c3d9849b0f",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "b74ddd14-6340-4840-95c2-db12554843e5",
                            RoleId = "8398a233-f6b9-4361-977c-da6a3e9c2bbe"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LibSys.Models.Entities.Book", b =>
                {
                    b.HasOne("LibSys.Models.Entities.BookDefinition", "BookDefinition")
                        .WithMany()
                        .HasForeignKey("BookDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookDefinition");
                });

            modelBuilder.Entity("LibSys.Models.Entities.Borrowing", b =>
                {
                    b.HasOne("LibSys.Models.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibSys.Models.Entities.Reader", "Reader")
                        .WithMany()
                        .HasForeignKey("ReaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("LibSys.Models.Entities.Reader", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
